'use strict';
const KEY='exs101-fitness-assessment-v1';
const blank=()=>({courseRevision:1,version:1,meta:{},tests:{},synthesis:{},detective:'',compare:{},skipBody:false,view:'start',active:null,step:0});
let state=blank(),storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===1&&saved.meta&&saved.tests&&saved.synthesis){state={...blank(),...saved,courseRevision:saved.courseRevision??0};if(!ASSESSMENTS.some(a=>a.id===state.active))state.active=null;state.view='start';}}catch(e){storageOK=false;}
function migrateCourse(){for(const d of Object.values(state.tests)){if(d.values?.notes)d.values.notes=d.values.notes.replace('Saved before the Canvas protocol update. Review the current procedure with your instructor before reusing these results.','Saved before the test procedure changed. Review the current directions before reusing these results.');}if(state.courseRevision===1)return;for(const d of Object.values(state.tests)){d.complete=false;d.confirmed=false;d.values.notes=[d.values.notes,'Saved before the test procedure changed. Review the current directions before reusing these results.'].filter(Boolean).join(' ');}state.courseRevision=1;}
migrateCourse();
for(const d of Object.values(state.tests)){if(d.values&&d.values.protocolChanged===undefined&&d.values.notes?.trim())d.values.protocolChanged=true;}
function hasProtocolChange(d){return d.values.protocolChanged===true;}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v!==''&&v!=null&&Number.isFinite(Number(v))?Number(v):null;
const aById=id=>ASSESSMENTS.find(a=>a.id===id);
const data=id=>(state.tests[id]??={values:{},writing:{},confirmed:false,complete:false,include:true});
function save(announce=false){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;if(announce)$('#save-status').textContent='Progress saved on this device. It is not sent to your instructor.';}catch(e){storageOK=false;$('#save-status').textContent='Browser saving is unavailable. Keep this page open and download a progress backup before leaving.';}}
function field(key,label,value,type='text',opts={}){const id='field-'+key.replace(/[^a-zA-Z0-9]/g,'-');return `<div class="field"><label for="${id}">${esc(label)}</label>${type==='textarea'?`<textarea id="${id}" data-key="${esc(key)}">${esc(value)}</textarea>`:type==='select'?`<select id="${id}" data-key="${esc(key)}">${opts.options.map(([v,l])=>`<option value="${esc(v)}" ${String(value??'')===v?'selected':''}>${esc(l)}</option>`).join('')}</select>`:`<input id="${id}" data-key="${esc(key)}" type="${type}" value="${esc(value)}" ${type==='number'?`min="${opts.min??0}" max="${opts.max??10000}" step="${opts.step??'any'}"`:''}>`}${opts.hint?`<p class="hint">${esc(opts.hint)}</p>`:''}</div>`;}
function check(key,label,checked){return `<div class="field"><label><input type="checkbox" data-key="${esc(key)}" ${checked?'checked':''}>${esc(label)}</label></div>`;}
function studentSources(a){return a.sources.filter(k=>!['course','class'].includes(k));}
function sourceLink(key){const s=SOURCES[key];return s.url?`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.studentTitle||s.title)} (opens in a new tab)</a>`:esc(s.studentTitle||s.title);}
function errors(items){const el=$('#errors');el.innerHTML=items.length?`<div class="error" role="alert"><strong>Please check:</strong><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'';if(items.length){el.focus();}}
function metaErrors(){return ['student','group','date'].filter(k=>!state.meta[k]?.trim()).map(k=>({student:'Enter your student name.',group:'Enter your lab group/section.',date:'Enter the lab date.'}[k]));}
function ageBand(age){return age<18?null:age<=25?0:age<=35?1:age<=45?2:age<=55?3:age<=65?4:5;}
const bandLabels=['18–25','26–35','36–45','46–55','56–65','66+'];
function percentileBand(score,thresholds,percentiles,lowerBetter=false){
 const pairs=thresholds.map((t,i)=>[t,percentiles[i]]);let exact=pairs.filter(([t])=>Math.abs(score-t)<1e-8);
 if(exact.length)return exact.length===1?`At the published ${exact[0][1]}th percentile anchor`:`At shared published anchors: ${Math.min(...exact.map(x=>x[1]))}th–${Math.max(...exact.map(x=>x[1]))}th percentiles`;
 if(lowerBetter){if(score<pairs[0][0])return 'Beyond the highest published anchor (no exact percentile assigned)';if(score>pairs.at(-1)[0])return 'Beyond the lowest published anchor (no exact percentile assigned)';}
 else{if(score<pairs[0][0])return `Below the published ${pairs[0][1]}th percentile anchor`;if(score>pairs.at(-1)[0])return `Above the published ${pairs.at(-1)[1]}th percentile anchor`;}
 for(let i=1;i<pairs.length;i++)if(score>pairs[i-1][0]&&score<pairs[i][0])return `Between published ${Math.min(pairs[i-1][1],pairs[i][1])}th and ${Math.max(pairs[i-1][1],pairs[i][1])}th percentile anchors`;
 return 'No exact percentile assigned';
}
function best(v){const ns=['trial1','trial2','trial3'].map((k,i)=>({value:number(v[k]),trial:i+1})).filter(x=>x.value!==null);if(!ns.length)return null;const top=ns.reduce((best,x)=>x.value>best.value?x:best);return {...top,count:ns.length};}
function comparison(a,v){const sex=v.sex,age=number(v.age),b=ageBand(age??0),descriptive=reason=>({type:'descriptive',text:'Descriptive result — no normative classification assigned',reason});
 const course=courseComparison(a,v);if(course)return course;
 if(a.id==='rockport'){
  if(!['male','female'].includes(sex))return descriptive('The selected equation requires its original male/female reference variable. Without that variable, report the measured walking performance.');
  if(['weight','minutes','seconds','hr','age'].some(k=>number(v[k])===null))return {type:'pending',text:'Enter the measured variables to calculate the estimate.'};
  const time=Number(v.minutes)+Number(v.seconds)/60;
  if(age<18||age>69)return descriptive('The course equation age ranges are 18–29 and 30–69. No extrapolation is made.');
  const kg=Number(v.weight)*(v.weightUnit==='lb'?0.45359237:1);
  const value=age<30?88.768+8.892*(sex==='male'?1:0)-.2109*kg-1.4537*time-.1194*Number(v.hr):132.853-.1692*kg-.3877*age+6.315*(sex==='male'?1:0)-3.2649*time-.1565*Number(v.hr);
  if(value<=0)return descriptive('These inputs produce a non-positive estimate. Check the units, time, and heart rate; do not interpret this as a valid VO₂max.');
  return {type:'prediction',text:`Estimated VO₂max — not directly measured: ${value.toFixed(1)} mL/kg/min`,value,reason:vo2Context(value,v),equation:age<30?`88.768 + 8.892 × sex(1 male/0 female) − 0.2109 × mass(kg) − 1.4537 × time(decimal min) − 0.1194 × immediate finish HR. Mass: ${kg.toFixed(2)} kg; time: ${time.toFixed(3)} min.`:`132.853 − 0.1692 × mass(kg) − 0.3877 × age + 6.315 × sex(1 male/0 female) − 3.2649 × time(decimal min) − 0.1565 × HR(beats/min). Time used: ${time.toFixed(3)} min; mass used: ${kg.toFixed(2)} kg.`};
 }
 if(a.id==='queens'){
  if(!['male','female'].includes(sex)||v.cadence!==(sex==='male'?'24':'22'))return descriptive('No prediction is calculated because the reference variable/cadence does not match the selected equation. Record the pulse and performed protocol.');
  if(number(v.pulse)===null)return {type:'pending',text:'Enter the 15-second recovery pulse count.'};
  const hr=Number(v.pulse)*4,value=sex==='male'?111.33-.42*hr:65.81-.1847*hr;
  if(value<=0)return descriptive('These inputs produce a non-positive estimate. Check the pulse count and protocol before interpreting it.');
  return {type:'prediction',text:`Estimated VO₂max — not directly measured: ${value.toFixed(1)} mL/kg/min`,value,reason:vo2Context(value,v)+` Recovery pulse: ${v.pulse} beats in 15 seconds × 4 = ${hr} beats/min. This estimates VO₂max; it does not measure respiratory gases.`,equation:sex==='male'?'Male equation: 111.33 − 0.42 × recovery HR(beats/min).':'Female equation: 65.81 − 0.1847 × recovery HR(beats/min).'};
 }
 if(a.kind!=='norm')return descriptive(a.limit);
 if(!['male','female'].includes(sex))return descriptive('No reference category selected. The actual performance remains reportable.');
 if(a.id==='ymca'){
  if(b===null)return descriptive('The implemented reference table begins at age 18. No extrapolation is made.');
  if(number(v.hr)===null)return {type:'pending',text:'Record the full-minute recovery count.'};
  return {type:'norm',text:percentileBand(Number(v.hr),STEP_NORMS[sex][b],STEP_PERCENTILES,true),population:`YMCA adult ${sex} reference, age ${bandLabels[b]}; 12-inch step, 24 cycles/min, 3 minutes, full-minute recovery count.`,anchors:STEP_NORMS[sex][b],percentiles:STEP_PERCENTILES,unit:'recovery beats',reason:'Lower recovery counts correspond to higher published percentile anchors. No interpolation or extrapolation is used. Reference percentiles describe this test, not overall fitness.',source:'ace'};
 }
 if(a.id==='pushup'){
  if(age===null||age<20||age>=60)return descriptive('The implemented unambiguous age groups are 20–59. No classification is assigned outside these groups; the published 60–69 female ranges overlap.');
  if(v.version!==(sex==='male'?'standard':'modified'))return descriptive('The performed push-up version does not match this reference category. Repetitions remain descriptive.');
  if(number(v.reps)===null)return {type:'pending',text:'Record correctly completed repetitions.'};
  const i=Math.floor(age/10)-2,thresholds=PUSH_NORMS[sex][i],names=['Needs improvement','Fair','Good','Very good','Excellent'];let cat=0;thresholds.forEach(t=>{if(Number(v.reps)>=t)cat++;});
  return {type:'norm',text:`Published category: ${names[cat]}`,population:`CSEP (2003), reproduced by ACE: ${sex}, age ${20+i*10}–${29+i*10}, ${v.version} push-ups to fatigue.`,reason:'These are the source’s category names, not a judgment about the person or their overall health. Reference-sample recruitment details are not given in the ACE summary.',source:'ace',categories:names,thresholds};
 }
 if(a.id==='sitreach'){
  if(v.convention!=='ace15')return descriptive('This scale/zero point does not match the ACE yardstick reference. No conversion is used to imply that different protocols are equivalent.');
  if(b===null||age===65)return descriptive('An age-matched comparison is unavailable below age 18 or at age 65.');
  const result=best({...v,trial3:''});if(!result)return {type:'pending',text:'Record at least one valid trial.'};
  if(result.count<2)return {type:'pending',text:'Record both valid trials for the selected sit-and-reach protocol.'};
  const inch=result.value/(v.unit==='cm'?2.54:1);
  return {type:'norm',text:percentileBand(inch,REACH_NORMS[sex][b],[10,20,30,40,50,60,70,80,90]),population:`YMCA adult ${sex} reference, age ${bandLabels[b]}; ACE yardstick, heels at 15 inches; best of two trials.`,anchors:REACH_NORMS[sex][b],percentiles:[10,20,30,40,50,60,70,80,90],unit:'inches on yardstick',reason:'Comparison uses the scale reading in inches. Body proportions affect performance; no exact percentile is interpolated.',source:'ace'};
 }
 if(a.id==='plank'){
  if(v.college!=='yes'||age===null||age<18||age>25)return descriptive('No comparison is assigned outside this app’s conservative college-age context (18–25). That eligibility window is an app choice, not a validated age cutoff from the study.');
  if(number(v.time)===null)return {type:'pending',text:'Record the hold time.'};
  return {type:'norm',text:percentileBand(Number(v.time),PLANK_NORMS[sex],[10,20,30,40,50,60,70,80,90]),population:`Strand et al. (2014): college students; ${sex} reference, mean age about 20; prone forearm plank to fatigue/technique failure.`,anchors:PLANK_NORMS[sex],percentiles:[10,20,30,40,50,60,70,80,90],unit:'seconds',reason:'These are sample percentile anchors, not age-specific standards for all adults. Table 2 contains inconsistent subgroup counts; this app uses only its sex-specific time anchors.',source:'plank'};
 }
 return descriptive(a.limit);
}
function rawResult(a,v){
 if(a.id==='rockport')return `1 mile: ${v.minutes??'—'} min ${v.seconds??'—'} s; finish HR ${v.hr??'—'} beats/min`;
 if(a.id==='ymca')return `${v.hr??'—'} beats counted in 60 seconds`;
 if(a.id==='queens')return `${v.pulse??'—'} beats in 15 seconds; ${number(v.pulse)!==null?Number(v.pulse)*4:'—'} beats/min; ${v.cadence??'—'} cycles/min`;
 if(a.id==='plank')return `${v.time??'—'} seconds${Number(v.time)===360?' (test cap reached; time to failure unknown)':''}`;
 if(['sitreach','vertical','broad'].includes(a.id)){const r=best(a.id==='sitreach'?{...v,trial3:''}:v);return r?`Best: ${r.value} ${v.unit} (trial ${r.trial}); ${r.count} valid trial${r.count===1?'':'s'} (${(a.id==='sitreach'?['trial1','trial2']:['trial1','trial2','trial3']).filter(k=>number(v[k])!==null).map(k=>`${v[k]} ${v.unit}`).join(', ')})`:'No trials recorded';}
 if(a.id==='shoulder'){const side=k=>{const vals=[1,2,3].map(i=>number(v[k+i])).filter(x=>x!==null);return vals.length?`${Math.max(...vals)} ${v.unit||'cm'}; trials: ${vals.join(', ')} ${v.unit||'cm'}`:'not recorded';};return `Right hand on top: ${side('right')}; left hand on top: ${side('left')} (negative = gap, positive = overlap)`;}
 if(a.id==='bia')return `Estimated body fat: ${v.fat??'—'}%; device: ${v.device??'—'}`;
 if(a.id==='fit3d')return `${v.output==='fat'?'Estimated body fat':v.label||'Selected output'}: ${v.value??'—'} ${v.output==='fat'?'%':v.unit||''}; ${v.method||'method not selected'}; ${v.device||'device not recorded'}`;
 return `${v.reps??'—'} correct repetitions${a.id==='bench'?`; load: ${v.load==='other'?v.loadOther:(v.load||'—')+' lb'}`:''}${a.id==='pushup'?`; ${v.version||'version not selected'}`:''}${a.id==='squat'&&v.adaptation?`; adaptation: ${v.adaptation}`:''}`;
}
function assessmentErrors(a,d,writing=true){const out=[],v=d.values;
 for(const f of a.fields){const value=v[f.key],ns=number(value);if(a.required.includes(f.key)&&(value==null||String(value).trim()===''))out.push(`Enter ${f.label}.`);
  if(f.type==='number'&&value!=null&&value!==''&&(ns===null||ns<f.min||ns>f.max||(f.step===1&&!Number.isInteger(ns))))out.push(`${f.label}: enter ${f.step===1?'a whole number':'a number'} from ${f.min} to ${f.max}.`);
 }
 if(hasProtocolChange(d)&&!v.notes?.trim())out.push('Describe the change to the test procedure.');
 if(a.id==='situp'&&['49','43'].includes(v.cap)&&number(v.reps)>Number(v.cap))out.push('The count exceeds the selected repetition cap. Check the count or cap.');
 if(!d.confirmed)out.push('Confirm that you followed the recorded protocol.');
 if(a.id==='vertical'&&['trial1','trial2','trial3'].some(k=>number(v[k])===null))out.push('Record all three valid vertical jump trials.');
 if(a.id==='sitreach'&&v.convention==='box'&&!v.box?.trim())out.push('Describe your box/zero-point convention.');
 if(a.id==='sitreach'&&v.convention!=='toes0'&&['trial1','trial2','trial3'].some(k=>number(v[k])!==null&&number(v[k])<0))out.push('Negative readings are available only for the toes-at-zero convention.');
 if(a.id==='rockport'&&number(v.minutes)===0&&number(v.seconds)===0)out.push('Walking time must be greater than zero.');
 if(a.id==='bench'&&v.load==='other'&&!v.loadOther?.trim())out.push('Record the other load and units.');
 if(a.id==='fit3d'){if(v.output==='other'&&(!v.label?.trim()||!v.unit?.trim()))out.push('Name the selected output and its units.');if(v.output==='fat'&&(number(v.value)>100||v.method!=='estimate'))out.push('Body-fat percentage must be 0–100 and identified as a modeled estimate.');}
 const c=reportComparison(a,d);if(c.type==='pending')out.push(c.text);
 if(writing){if(!d.writing.suggest?.trim())out.push('Explain what this result suggests.');if(!d.writing.limit?.trim())out.push('Explain what this assessment cannot establish.');if(a.extra&&!d.writing.extra?.trim())out.push('Complete the assessment comparison/reflection prompt.');if(c.type==='norm'&&!state.detective.trim())out.push('Complete the one-time reference-matching response.');}
 return [...new Set(out)];
}
const completed=()=>ASSESSMENTS.filter(a=>state.tests[a.id]?.complete&&!assessmentErrors(a,state.tests[a.id]).length);
function progress(){const counts=Object.fromEntries(Object.keys(GROUPS).map(g=>[g,completed().filter(a=>a.group===g).length]));const base=Object.entries(GROUPS).reduce((s,[g,v])=>s+Math.min(v.need,counts[g]),0);const extra=Object.entries(GROUPS).reduce((s,[g,v])=>s+(v.need?Math.max(0,counts[g]-v.need):0),0);return {counts,base,extra,credit:base+Math.min(1,extra),ready:base===5&&extra>=1};}
function toolbar(){return `<div class="toolbar"><button class="secondary" data-action="dashboard">Assessment Dashboard</button><div class="actions"><button class="secondary" data-action="save">Save Progress</button><button class="secondary" data-action="backup">Download Progress Backup</button><button class="secondary" data-action="reset">Start Over</button></div></div><p class="hint">Progress saves automatically on this device. A progress backup lets you continue on another device; it is not the lab report you submit. It is not sent to your instructor. Clear it after using a shared device.</p>`;}
function start(){return `<section class="panel"><h2 tabindex="-1">Prepare Your Lab</h2><p>This is a digital laboratory notebook and report builder. Enter actual assessment results collected during class.</p><div class="note"><h3>Your Data &amp; Privacy</h3><p>Your assessment data are stored on this device while you complete the lab. Your instructor does not receive your results through this website. You choose what is submitted when you upload your completed Assessment Profile PDF to Canvas.</p><p>No account or medical information is needed. Browser settings and Canvas embeds can affect local saving; a progress backup is available.</p></div><div class="grid">${field('meta.student','Student name',state.meta.student)}${field('meta.group','Lab group/section',state.meta.group)}${field('meta.date','Date',state.meta.date,'date')}</div><p>Use assessments approved by your instructor, follow station safety directions, and allow recovery between tests. Stop for pain, dizziness, or loss of control and tell your instructor. Ask for an alternative when an assessment is unsuitable.</p><p><strong>Required:</strong> 1 cardiorespiratory + 2 muscular endurance + 1 flexibility + 1 power + 1 additional assessment = 6 distinct assessments.</p><p><strong>Body Composition — Optional.</strong> You may complete it if available and you choose to participate. You may also skip it. No explanation is required.</p><div class="actions"><button data-action="begin">${Object.keys(state.tests).length?'Continue My Lab':'Open Assessment Dashboard'}</button><button class="secondary" data-action="import">Restore Progress Backup</button></div><input type="file" id="import-file" accept="application/json,.json" hidden></section>`;}
function dashboard(){const p=progress();return `<section class="panel"><h2 tabindex="-1">Assessment Dashboard</h2><p>${p.ready?'<strong>Required Assessments Complete</strong>':`<strong>${p.credit} of 6 required assessments completed</strong>`}</p><progress max="6" value="${p.credit}" aria-label="Required assessment progress">${p.credit} of 6</progress><p class="hint">Completion includes recording your result, interpretation, and limitation. More assessments do not produce a better fitness score.</p><div class="grid">${Object.entries(GROUPS).filter(([g])=>g!=='body').map(([g,group])=>`<section class="panel category"><h3>${group.name}</h3><p class="badge">${Math.min(group.need,p.counts[g])} of ${group.need} complete${p.counts[g]>group.need?`; ${p.counts[g]-group.need} additional` :''}</p>${ASSESSMENTS.filter(a=>a.group===g).map(a=>`<button class="secondary" data-assessment="${a.id}">${a.name} — ${state.tests[a.id]?.complete&&!assessmentErrors(a,state.tests[a.id]).length?'✓ Complete':state.tests[a.id]?'In Progress':'Start'}</button>${state.tests[a.id]&&!state.tests[a.id].complete?`<p class="hint">${assessmentErrors(a,state.tests[a.id]).length} item(s) remaining; open to finish.</p>`:''}`).join('')}</section>`).join('')}<section class="panel category"><h3>Additional Assessment</h3><p class="badge">${Math.min(1,p.extra)} of 1 complete</p><p>Complete another distinct assessment from any required category. One assessment cannot fill two slots. Body composition does not count toward this requirement.</p></section><section class="panel category"><h3>Body Composition — Optional</h3><p>You may participate if available or skip this section. No explanation is required.</p>${state.skipBody?'<p>Skipped — optional.</p><button class="secondary" data-action="show-body">Show Optional Assessments</button>':ASSESSMENTS.filter(a=>a.group==='body').map(a=>`<button class="secondary" data-assessment="${a.id}">${a.name} — ${state.tests[a.id]?.complete?'Recorded':state.tests[a.id]?'In Progress':'Start'}</button>`).join('')+'<button class="secondary" data-action="skip-body">Skip Body Composition</button>'}</section></div><h3>My Assessment Profile</h3>${completed().length?`<ul>${completed().map(a=>`<li>✓ ${a.name} — ${GROUPS[a.group].name}: result recorded</li>`).join('')}</ul>`:'<p>Your completed assessments will appear here.</p>'}<div class="actions"><button data-action="synthesis" ${p.ready?'':'disabled'}>Looking Across Your Assessments</button><button class="secondary" data-action="info">Edit Lab Information</button></div>${!p.ready?'<p class="hint">Complete every required category and one additional assessment to unlock the final reflection.</p>':''}</section>`;}
function assessment(){const a=aById(state.active),d=data(a.id),s=state.step;
 const steps=['Prepare','Record','Interpret'];return `<section class="panel"><h2 tabindex="-1">${a.name}</h2><p>${GROUPS[a.group].name}</p><nav class="steps" aria-label="Assessment steps">${steps.map((name,i)=>`<button data-step="${i}" aria-current="${i===s?'step':'false'}">${i+1}. ${name}</button>`).join('')}</nav>${s===0?prepareAssessment(a,d):s===1?recordAssessment(a,d):interpretAssessment(a,d)}<div class="actions">${s>0?`<button class="secondary" data-step="${s-1}">Back</button>`:''}${s<2?`<button data-step="${s+1}">Continue to ${steps[s+1]}</button>`:`<button data-action="complete">Save Completed Assessment</button>`}<button class="secondary" data-action="dashboard">Save &amp; Return to Dashboard</button></div></section>`;
}
function testDirections(a){const g=STATION_GUIDES[a.id];return `<div class="station-guide"><h3>Set Up</h3><p><strong>Equipment:</strong> ${esc(g.equipment)}</p><p><strong>Who does what:</strong> ${esc(g.roles)}</p>${activityImage(a)}<h3>Perform the Test</h3><ol>${g.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="note"><strong>What counts:</strong> ${esc(g.counts)}</p></div>`;}
function activityImage(a){const im=ACTIVITY_IMAGES[a.id];if(!im)return '';return `<figure class="activity-image"><img src="${esc(im.file)}" alt="${esc(im.alt)}" loading="lazy" width="600"><figcaption>${esc(im.caption)} <details><summary>Image credit</summary><a href="${esc(im.source)}" target="_blank" rel="noopener noreferrer">${esc(im.author)} / Wikimedia Commons</a> · ${im.licenseURL?`<a href="${esc(im.licenseURL)}" target="_blank" rel="noopener noreferrer">${esc(im.license)}</a>`:esc(im.license)}</details></figcaption></figure>`;}
function prepareAssessment(a,d){return `<h3>What This Measures</h3><p>${esc(a.measure)}</p>${testDirections(a)}${a.check?`<details><summary>Quick Practice Check</summary>${field('practice',a.check[0],d.practice,'select',{options:[['','Choose an answer'],...a.check[1].map((t,i)=>[String(i),t])]})}<p id="check-feedback" class="check-feedback" role="status">${practiceFeedback(a,d.practice)}</p></details>`:''}${studentSources(a).length?`<details><summary>Sources</summary><ul>${studentSources(a).map(k=>`<li>${sourceLink(k)}</li>`).join('')}</ul></details>`:''}`;}

function practiceFeedback(a,v){if(!a.check||v==null||v==='')return '';return Number(v)===a.check[2]?'Correct. Use this timing/protocol while testing.':'Review “Perform the Test” and try again. This check is not graded.';}
function resultContents(a,d){const v=d.values,c=reportComparison(a,d);let main=rawResult(a,v),conversion='',label='Recorded performance';
 if(c.type==='prediction'){main=c.value.toFixed(1)+' mL/kg/min';label='Estimated VO₂max';}
 if(['broad','vertical','sitreach'].includes(a.id)){const r=best(a.id==='sitreach'?{...v,trial3:''}:v);if(r&&v.unit){label=a.id==='sitreach'?'Best reach reading':a.id==='broad'?'Best jump distance':'Best jump height';main=r.value+' '+v.unit+' (trial '+r.trial+')';const unit=a.id==='sitreach'?'in':'cm',converted=v.unit===unit?r.value:unit==='cm'?r.value*2.54:r.value/2.54;conversion=a.id==='sitreach'&&v.convention!=='ace15'?'This zero point does not match the chart; converting units does not make the procedures equivalent.':`Compare with the chart: ${converted.toFixed(1)} ${unit}${v.unit!==unit?' (converted from '+r.value+' '+v.unit+')':''}.`;}}
 if(a.id==='shoulder'){conversion='The chart uses inches. '+['right','left'].map(side=>{const values=[1,2,3].map(i=>number(v[side+i])).filter(x=>x!==null);return values.length?side+' hand on top: '+(Math.max(...values)/(v.unit==='in'?1:2.54)).toFixed(2)+' in':'';}).filter(Boolean).join('; ')+'.';}
 if(a.id==='situp'&&['49','43'].includes(v.cap)&&number(v.reps)===Number(v.cap))main+=' — cap reached; uncapped maximum unknown';
 return `<h3>Your Results</h3><p class="hint">${esc(label)}</p><p class="result-value">${esc(main)}</p>${c.type==='prediction'?`<p>Recorded: ${esc(rawResult(a,v))}</p><p class="hint">Calculated from your recorded data; not directly measured with respiratory gases.</p>`:''}${conversion?`<p class="unit-conversion">${esc(conversion)}</p>`:''}<p><strong>${esc(c.type==='pending'?c.text:c.type==='prediction'?'Use this estimate with the VO₂max chart below.':c.text)}</strong></p>${c.reason?`<p class="hint">${esc(c.reason)}</p>`:''}`;
}
function resultPanel(a,d,live=false){return `<section class="result result-panel" ${live?'id="record-result" role="status" aria-live="polite"':'aria-label="Your results"'}>${resultContents(a,d)}</section>`;}
function recordAssessment(a,d){return `<details><summary>Test directions</summary>${testDirections(a)}</details><h3>Record your data</h3><p class="hint">Choose units, then enter your measurements.</p><div class="grid">${a.fields.map(f=>field('values.'+f.key,f.label,d.values[f.key],f.type,f)).join('')}</div>${check('values.protocolChanged','I changed the test procedure.',hasProtocolChange(d))}${field('values.notes','Notes — optional unless you changed the procedure',d.values.notes,'textarea')}${check('confirmed','I followed the directions or recorded my changes.',d.confirmed)}${a.group==='body'?check('include','Include this optional assessment in my report',d.include!==false):''}${resultPanel(a,d,true)}<p class="hint">Reference categories reproduce the source’s male/female groups. You may select no reference comparison where offered.</p>`;}
function detective(){return `<section class="note"><h3>Match the Reference — Answer Once</h3><p>Check that the test procedure, age group, and reference population fit your result.</p>${field('detective','Why must a reference chart match the test procedure and reference population before you use it to interpret a result?',state.detective,'textarea')}</section>`;}

function normDetails(c){return `<details><summary>About this reference</summary><p>${esc(c.population)}</p>${c.source&&!['course','class'].includes(c.source)?`<p>${sourceLink(c.source)}</p>`:''}<p>Reference categories describe this test, not overall health or fitness.</p></details>`;}
function interpretAssessment(a,d){const c=reportComparison(a,d),e=assessmentErrors(a,d);return `${resultPanel(a,d)}<h3>Compare</h3><p class="hint">Compare your result with the matching chart. The 50th percentile is the reference sample’s median.</p>${c.population?`<p class="note"><strong>Your reference group:</strong> ${esc(c.population)}</p>`:''}${referenceCharts(a,d.values)}${c.equation?`<details><summary>How the estimate was calculated</summary><p>${esc(c.equation)}</p><ul>${studentSources(a).map(k=>`<li>${sourceLink(k)}</li>`).join('')}</ul></details>`:''}${c.type==='norm'?`${!state.detective.trim()?detective():''}${normDetails(c)}`:''}<p class="hint">${esc(a.limit)}</p><h3>Explain</h3>${field('writing.suggest','What does your result suggest? Cite your result and comparison.',d.writing.suggest,'textarea')}${field('writing.limit','What is one limitation of this test?',d.writing.limit,'textarea')}${a.extra?field('writing.extra',a.extra,d.writing.extra,'textarea'):''}<details><summary>Assessment completion checklist</summary><ul>${e.length?e.map(x=>`<li>${esc(x)}</li>`).join(''):'<li>Measurements, procedure confirmation, and responses are complete.</li>'}</ul></details>`;}

function reportComparison(a,d){return hasProtocolChange(d)?{type:'descriptive',text:'Descriptive result — no normative classification assigned',reason:'Procedure changed; report measured performance descriptively.'}:comparison(a,d.values);}
function synthesisPrompts(){const list=completed().filter(a=>a.group!=='body'||data(a.id).include!==false),norm=list.some(a=>reportComparison(a,data(a.id)).type==='norm'),estimate=list.some(a=>['prediction','estimate'].includes(reportComparison(a,data(a.id)).type)||a.id==='bia'||(a.id==='fit3d'&&data(a.id).values.method==='estimate'));return [
 'Choose two assessments that provided very different kinds of information. What did each measure?',
 norm?'Choose one normative comparison from today’s lab. What does that comparison allow you to conclude? What does it NOT allow you to conclude?':'Your selected results do not include a normative comparison. Choose one result: what protocol and reference-population information would you need before assigning one? What would that comparison still NOT establish?',
 estimate?'Identify one value from today’s lab that was estimated rather than directly measured. How was the estimate produced, and why does the distinction between measurement and estimation matter?':'Your selected tests did not produce a prediction-equation/body-composition estimate. Choose one directly recorded result. How would estimating VO₂max from field performance differ from measuring respiratory gases, and why does that distinction matter?',
 'Someone looks at all these results and asks, “So, am I fit?” Why is that question harder to answer than it sounds?'
 ];}
function methodsIncluded(){return completed().some(a=>a.id==='bia'&&data(a.id).include!==false)&&completed().some(a=>a.id==='fit3d'&&data(a.id).include!==false);}
function comparisonPrompts(){return ['Were the results identical? If the outputs have different units or describe different characteristics, can they be compared directly?','Why might two methods assessing the same person produce different estimates?','Does a difference automatically mean one method is “wrong”? Explain.'];}
function synthesis(){return `<section class="panel"><h2 tabindex="-1">Looking Across Your Assessments</h2><p>A test gives evidence about a specific characteristic. It does not define the person. Write your own conclusions using the results you collected.</p>${synthesisPrompts().map((q,i)=>field('synthesis.q'+i,`${i+1}. ${q}`,state.synthesis['q'+i],'textarea')).join('')}${methodsIncluded()?`<h3>Compare the Methods</h3><p>${esc(rawResult(aById('bia'),data('bia').values))}</p><p>${esc(rawResult(aById('fit3d'),data('fit3d').values))}</p>${comparisonPrompts().map((q,i)=>field('compare.q'+i,q,state.compare['q'+i],'textarea')).join('')}`:''}<div class="actions"><button data-action="review" ${reportMissing().length?'disabled':''}>Generate My Assessment Profile</button><button class="secondary" data-action="dashboard">Return to Dashboard</button></div><p id="report-readiness" class="hint">${reportMissing().length?'Complete the four synthesis responses'+(methodsIncluded()?' and method comparison':'')+' to generate your profile.':'Your profile is ready to review.'}</p></section>`;}
function reportMissing(){const out=[...metaErrors()];if(!progress().ready)out.push('Complete every required assessment category and an additional assessment.');synthesisPrompts().forEach((q,i)=>{if(!state.synthesis['q'+i]?.trim())out.push(`Complete synthesis response ${i+1}.`);});if(methodsIncluded())comparisonPrompts().forEach((q,i)=>{if(!state.compare['q'+i]?.trim())out.push(`Complete method comparison ${i+1}.`);});return out;}
function reportBlocks(){
 const list=completed().filter(a=>a.group!=='body'||data(a.id).include!==false),blocks=[{tag:'H1',text:'FITNESS ASSESSMENT | LABORATORY REPORT'},{tag:'P',text:`${state.meta.student} | ${state.meta.group} | ${state.meta.date}`}];
 for(const a of list){const d=data(a.id),c=reportComparison(a,d);blocks.push({tag:'H2',text:a.name});
 const rows=a.fields.filter(f=>d.values[f.key]!=null&&d.values[f.key]!=='').map(f=>{let value=d.values[f.key];if(f.type==='select')value=f.options.find(o=>o[0]===value)?.[1]||value;return [f.label.replace(' — optional',''),String(value)];});rows.push(['Result',rawResult(a,d.values)]);if(['broad','vertical','sitreach'].includes(a.id)){const r=best(a.id==='sitreach'?{...d.values,trial3:''}:d.values),unit=a.id==='sitreach'?'in':'cm';if(r&&d.values.unit)rows.push(['Result in chart units',((d.values.unit===unit?r.value:unit==='cm'?r.value*2.54:r.value/2.54).toFixed(1))+' '+unit]);}if(c.type==='norm'||c.type==='prediction'){let reference=c.text;if(c.type==='prediction'){const match=c.reason?.match(/(?:At|Between|Below|Above|Beyond)[^.]*percentile[^.]*/i);if(match)reference+='; '+match[0];}rows.push(['Reference comparison',reference]);}blocks.push({tag:'TABLE',text:rows.map(r=>r.join(': ')).join('\n'),headers:['Measurement','Value'],rows});
 const note=d.values.notes?.replace('Saved before the test procedure changed. Review the current directions before reusing these results.','').replace('Saved before the Canvas protocol update. Review the current procedure with your instructor before reusing these results.','').trim();if(note)blocks.push({tag:'P',text:'Testing note: '+note});
 blocks.push({tag:'H3',text:'Interpretation'},{tag:'P',text:d.writing.suggest},{tag:'H3',text:'Limitation'},{tag:'P',text:d.writing.limit});if(a.extra)blocks.push({tag:'H3',text:a.id==='rockport'?'Comparison with direct VO₂ measurement':'Factors affecting the estimate'},{tag:'P',text:d.writing.extra});
 }
 if(list.some(a=>reportComparison(a,data(a.id)).type==='norm'))blocks.push({tag:'H2',text:'Using Reference Data'},{tag:'H3',text:'Matching the reference to the test'},{tag:'P',text:state.detective});
 blocks.push({tag:'H2',text:'Across My Assessments'});const headings=['Different Assessments','Interpreting a Reference Comparison','Measurements and Estimates','What These Results Say About Fitness'];synthesisPrompts().forEach((q,i)=>blocks.push({tag:'H3',text:headings[i]},{tag:'P',text:state.synthesis['q'+i]}));
 if(methodsIncluded()){blocks.push({tag:'H2',text:'Body-Composition Method Comparison'},{tag:'P',text:rawResult(aById('bia'),data('bia').values)+'\n'+rawResult(aById('fit3d'),data('fit3d').values)});comparisonPrompts().forEach((q,i)=>blocks.push({tag:'H3',text:q},{tag:'P',text:state.compare['q'+i]}));}
 const names={ace:'ACE / YMCA / CSEP assessment tables',rockport:'Kline et al. (1987)',dolgener:'Dolgener et al. (1994)',courseNSCA:'Haff & Triplett (2016), NSCA',queens:'Queens College step-test protocol',queensStudy:'Queens College prediction equations',situp:'Schoenfeld & Snarr (2021), NSCA',bia:'NIH BIA guidance',fit3d:'Fit3D documentation',jump:'NSCA jump assessment guidance'};const refs=[...new Set(list.flatMap(a=>a.sources))].filter(k=>names[k]).map(k=>names[k]);if(list.some(a=>['rockport','queens'].includes(a.id)))refs.push('ACSM VO₂max reference table');if(refs.length)blocks.push({tag:'P',small:true,text:'References: '+refs.join('; ')+'.'});return blocks;
}
function reportHTML(standalone=false){return reportBlocks().map(b=>{if(b.tag==='TABLE')return `<div class="scroll"><table><caption>Assessment measurements and result</caption><thead><tr>${b.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${b.rows.map(r=>`<tr><th scope="row">${esc(r[0])}</th><td>${esc(r[1])}</td></tr>`).join('')}</tbody></table></div>`;const tag=(standalone?{H1:'h1',H2:'h2',H3:'h3',P:'p'}:{H1:'h2',H2:'h3',H3:'h4',P:'p'})[b.tag];return `<${tag}>${esc(b.text)}</${tag}>`;}).join('');}
function report(){return `<section class="panel"><h2 tabindex="-1">Review Your Assessment Profile</h2><p>Review your results and your own responses before downloading. You can return to any assessment to revise it.</p><div class="actions"><button data-action="pdf">Download Lab Report PDF</button><button class="secondary" data-action="synthesis">Edit Synthesis</button></div><p>Download your PDF, then upload it to the Fitness Assessment Lab assignment in Canvas.</p><details><summary>Optional body-composition report choices</summary><p>Optional results are included only when selected. You may exclude them without explanation.</p>${completed().filter(a=>a.group==='body').map(a=>check('include-'+a.id,'Include '+a.name,data(a.id).include!==false)).join('')||'<p>No optional results selected.</p>'}</details><article class="report">${reportHTML()}</article></section>`;}
function setValue(key,value){if(key.startsWith('include-')){data(key.slice(8)).include=value;save();render();return;}
 if(key.startsWith('meta.'))state.meta[key.slice(5)]=value;
 else if(key.startsWith('synthesis.'))state.synthesis[key.slice(10)]=value;
 else if(key.startsWith('compare.'))state.compare[key.slice(8)]=value;
 else if(key==='detective')state.detective=value;
 else{const d=data(state.active);if(key.startsWith('values.')){d.values[key.slice(7)]=value;d.complete=false;}else if(key.startsWith('writing.')){d.writing[key.slice(8)]=value;d.complete=false;}else{d[key]=value;if(key==='confirmed')d.complete=false;}}
 save();
 if(key==='practice')$('#check-feedback').textContent=practiceFeedback(aById(state.active),value);
 if(state.view==='assessment'&&state.step===1&&$('#record-result'))$('#record-result').innerHTML=resultContents(aById(state.active),data(state.active));
 if(state.view==='synthesis'){const ready=!reportMissing().length;const btn=$('[data-action=review]');btn.disabled=!ready;$('#report-readiness').textContent=ready?'Your profile is ready to review.':'Complete the synthesis responses'+(methodsIncluded()?' and method comparison':'')+' to generate your profile.';}
}
function render(focus=true){if(state.view==='assessment'&&!state.active)state.view='dashboard';if(['synthesis','report'].includes(state.view)&&!progress().ready)state.view='dashboard';
 $('#app').innerHTML=`${state.view==='start'?'':toolbar()}<div id="errors" tabindex="-1"></div>${state.view==='start'?start():state.view==='dashboard'?dashboard():state.view==='assessment'?assessment():state.view==='synthesis'?synthesis():report()}`;
 $('#app').querySelectorAll('[data-key]').forEach(el=>el.addEventListener(el.type==='checkbox'||el.tagName==='SELECT'?'change':'input',()=>setValue(el.dataset.key,el.type==='checkbox'?el.checked:el.value)));
 $('#app').querySelectorAll('[data-assessment]').forEach(el=>el.onclick=()=>{state.active=el.dataset.assessment;data(state.active);state.view='assessment';state.step=1;save();render();});
 $('#app').querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>{state.step=Number(el.dataset.step);save();render();});
 $('#app').querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action));
 if($('#import-file'))$('#import-file').onchange=restore;
 if(focus){const h=$('#app h2');if(h){h.focus();h.scrollIntoView({block:'start'});}}
 if(!storageOK)$('#save-status').textContent='Browser saving is unavailable. Keep this page open and download a progress backup before leaving.';
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(ext){return 'EXS101-Assessment-Profile-'+(state.meta.student||'Student').replace(/[^a-z0-9_-]/gi,'-')+'.'+ext;}
function action(which){
 if(which==='begin'){const e=metaErrors();errors(e);if(e.length)return;state.view='dashboard';}
 if(which==='dashboard')state.view='dashboard';
 if(which==='info')state.view='start';
 if(which==='save'){save(true);return;}
 if(which==='reset'){if(!confirm('Start over and remove all saved assessment data and responses from this device?'))return;try{localStorage.removeItem(KEY);}catch(e){}state=blank();render();$('#save-status').textContent='Saved assessment data cleared from this device.';return;}
 if(which==='skip-body'){state.skipBody=true;for(const a of ASSESSMENTS.filter(a=>a.group==='body'))if(state.tests[a.id])state.tests[a.id].include=false;state.view='dashboard';}
 if(which==='show-body'){state.skipBody=false;}
 if(which==='synthesis'){if(!progress().ready)return;state.view='synthesis';}
 if(which==='complete'){const a=aById(state.active),d=data(a.id),e=assessmentErrors(a,d);errors(e);if(e.length)return;d.complete=true;state.view='dashboard';}
 if(which==='review'){const e=reportMissing();errors(e);if(e.length)return;state.view='report';}
 if(which==='pdf'){const e=reportMissing();errors(e);if(e.length)return;try{download(makeProfilePDF(reportBlocks(),state.meta),filename('pdf'));$('#save-status').textContent='PDF generated. Review and save it, then upload it to Canvas.';}catch(e){errors(['PDF generation failed. Your progress remains here. Try downloading again; your work is still saved here.']);}return;}
 if(which==='html'){const e=reportMissing();errors(e);if(e.length)return;download(new Blob([`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EXS101 Assessment Profile</title><style>body{font:17px/1.55 Arial,sans-serif;color:#1f2937;max-width:850px;padding:24px;margin:auto}p{white-space:pre-wrap;overflow-wrap:anywhere}h1{font-size:18px}h2{font-size:14px;text-transform:uppercase;border-top:1px solid #bac8d5;padding-top:10px;margin-top:24px}h3{font-size:13px}p,table{font-size:14px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bac8d5;padding:8px;text-align:left}thead th{background:#e8f3f8}.scroll{overflow-x:auto}h1,h2,h3{color:#1f2937}</style></head><body><main>${reportHTML(true)}</main></body></html>`],{type:'text/html'}),filename('html'));return;}
 if(which==='backup'){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'EXS101-Fitness-Progress.json');$('#save-status').textContent='Progress backup downloaded. It contains your entered assessment data; keep it private.';return;}
 if(which==='import'){$('#import-file').click();return;}
 save();render();
}
async function restore(event){const file=event.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('too large');const s=JSON.parse(await file.text());if(s.version!==1||!s.meta||!s.tests||!s.synthesis)throw Error('invalid');for(const a of ASSESSMENTS){const d=s.tests[a.id];if(d&&(!d.values||!d.writing))throw Error('invalid');}if(!confirm('Replace the current progress with this progress backup?'))return;state={...blank(),...s,courseRevision:s.courseRevision??0,view:'start',active:null};migrateCourse();save();render();$('#save-status').textContent='Progress restored. Check your lab information and continue.';}catch(e){errors(['This file is not a valid EXS101 Fitness Assessment Lab progress backup.']);}}
function vo2Context(value,v){const age=number(v.age);if(age===null||age<20||age>69)return 'Estimated, not directly measured. The supplied VO₂max table covers ages 20–69; no age-matched comparison is available.';return 'Estimated, not directly measured. VO₂max reference ('+v.sex+', age '+(Math.floor(age/10)*10)+'–'+(Math.floor(age/10)*10+9)+'): '+percentileBand(value,COURSE_VO2[v.sex][Math.floor(age/10)-2],COURSE_VO2_PERCENTILES)+'. Percentile bands are approximate comparisons, not exact individual ranks.';}
function courseComparison(a,v){if(a.id==='situp')return situpComparison(v);const sex=v.sex,age=number(v.age),desc=reason=>({type:'descriptive',text:'Descriptive result — no normative classification assigned',reason});
 if(a.id==='shoulder')return shoulderComparison(v);
 if(a.id==='pushup'){
  if(!['male','female'].includes(sex)||age===null||age<20||age>69||v.version!==(sex==='male'?'standard':'modified'))return desc('The reference requires ages 20–69 and a matched version/reference category.');
  const score=number(v.reps);if(score===null)return {type:'pending',text:'Record correct repetitions.'};
  const i=Math.floor(age/10)-2;
  if((sex==='male'&&i===1&&score>=20&&score<=21)||(sex==='female'&&i===4&&score===1))return desc('This score falls between overlapping categories, so no automatic category is assigned.');
  const tables={male:[[17,22,29,36],[12,17,20,30],[10,13,17,25],[7,10,13,21],[5,8,11,18]],female:[[10,15,21,30],[8,13,20,27],[5,11,15,24],[2,7,11,21],[1,5,12,17]]},thresholds=tables[sex][i],categories=['Needs improvement','Fair','Good','Very good','Excellent'];let index=0;thresholds.forEach(t=>{if(score>=t)index++;});return {type:'norm',text:'Published category: '+categories[index],population:`${sex} reference, ages ${20+i*10}–${29+i*10}, ${v.version} push-ups.`,reason:'Source category labels describe this assessment, not overall health. Ambiguous overlapping scores are withheld.',source:'courseNSCA',categories,thresholds};
 }
 if(!['bench','curlup'].includes(a.id))return null;
 if(!['male','female'].includes(sex))return desc('No reference category selected. Performance remains reportable.');
 if(age===null||age<(a.id==='bench'?18:20)||(a.id==='curlup'&&age>69))return desc('Age is outside the supplied table. No extrapolation is made.');
 if(a.id==='bench'&&v.load!==(sex==='male'?'80':'35'))return desc('The load performed does not match the selected reference.');
 const score=number(v.reps);if(score===null)return {type:'pending',text:'Record correct repetitions.'};
 const b=a.id==='bench'?ageBand(age):Math.floor(age/10)-2,anchors=(a.id==='bench'?COURSE_BENCH_ROWS:COURSE_CURL_ROWS).map(row=>row[b*2+(sex==='female'?1:0)]);
 return {type:'norm',text:percentileBand(score,anchors,COURSE_PERCENTILES),population:`${a.name}, ${sex} reference, age ${a.id==='bench'?bandLabels[b]:20+b*10+'–'+(29+b*10)}; ${a.id==='bench'?v.load+' lb, 60 beats/min':'age-matched marker spacing, 40 beats/min, maximum 75'}.`,anchors,percentiles:COURSE_PERCENTILES,unit:'correct repetitions',source:'courseNSCA',reason:'Percentile bands compare your repetitions with the reference table. Shared values and the test ceiling do not establish an exact individual rank.'};
}

function situpComparison(v){const score=number(v.reps),age=number(v.age),desc=reason=>({type:'descriptive',text:'Recorded performance — no automatic category',reason});if(score===null)return {type:'pending',text:'Enter your correct sit-up count.'};if(!['male','female'].includes(v.sex)||age===null||age<18||age===65)return desc('An age-matched reference comparison is unavailable for the selected group.');if(v.cap!==(v.sex==='male'?'49':'43'))return desc('The selected cap does not match this reference protocol.');if(score>Number(v.cap))return desc('The count exceeds the selected protocol cap.');const col=ageBand(age),matches=SITUP_RANGES[v.sex].map((row,i)=>{const range=row[col];if(range[0]==='>')return score>Number(range.slice(1))?i:-1;if(range[0]==='<')return score<Number(range.slice(1))?i:-1;const [lo,hi]=range.split('–').map(Number);return score>=lo&&score<=hi?i:-1;}).filter(i=>i>=0);if(matches.length!==1)return desc('This score has no single category in the reference table. Report your repetitions descriptively.');return {type:'norm',text:'Reference category: '+SITUP_CATEGORIES[matches[0]]+(score===Number(v.cap)?' (test cap reached)':''),population:`${v.sex} reference, age ${['18–25','26–35','36–45','46–55','56–65','65+'][col]}; 60-second full sit-up with anchored feet.`,reason:score===Number(v.cap)?'Your capped count does not establish your uncapped maximum.':'Compare only with the matching full sit-up protocol.',source:'situp'};}
function chartTable(caption,headers,rows){return `<div class="scroll" tabindex="0" role="region" aria-label="${esc(caption)}"><table class="norm-data"><caption>${esc(caption)}</caption><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>i===0?`<th scope="row">${esc(x)}</th>`:`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function shoulderComparison(v){
 if(!['male','female'].includes(v.sex))return {type:'descriptive',text:'Select a reference category to compare each shoulder result with the chart.',reason:'The chart remains available below; no category is assumed.'};
 const classify=(side)=>{const vals=[1,2,3].map(i=>number(v[side+i])).filter(x=>x!==null);if(vals.length<3)return 'record three trials';const inch=Math.max(...vals)/(v.unit==='in'?1:2.54),female=v.sex==='female',right=side==='right',excellent=female?(right?6:5):(right?5:4),goodMin=female?2:1,goodMax=excellent-1,fair=female?1:0;
 if(inch>excellent)return 'Excellent';if(inch>=goodMin&&inch<=goodMax)return 'Good';if(Math.abs(inch-fair)<1e-8)return 'Fair';if(inch<fair)return 'Low';return 'not covered by the supplied chart ranges';};
 return {type:'norm',text:`Shoulder reference: right hand up — ${classify('right')}; left hand up — ${classify('left')}.`,population:`Shoulder mobility chart, ${v.sex} reference; best of three trials per side, compared in inches.`,reason:'Negative = gap; positive = overlap. Some distances fall between chart categories and receive no automatic rating.',source:'course'};
}
function referenceCharts(a,v){let html='',note='',source='ACSM / NSCA assessment reference table.';const selected=['male','female'].includes(v.sex)?[v.sex]:['male','female'];
 if(['rockport','queens'].includes(a.id)){for(const sex of selected)html+=chartTable(`VO₂max reference — ${sex} (mL/kg/min)`,['Percentile','Category','20–29','30–39','40–49','50–59','60–69'],COURSE_VO2_PERCENTILES.map((p,i)=>[p+'th',p>=90?'Superior':p>=70?'Excellent':p>=50?'Good':p>=30?'Fair':p>=15?'Poor':'Very poor',...COURSE_VO2[sex].map(col=>col[i])]));note='Use the age column and reference category to locate the estimated VO₂max. A field-test estimate remains an estimate. A score between anchors does not have an exact percentile assigned.';}
 if(['bench','curlup'].includes(a.id)){const labels=a.id==='bench'?bandLabels:['20–29','30–39','40–49','50–59','60–69'],rows=a.id==='bench'?COURSE_BENCH_ROWS:COURSE_CURL_ROWS;for(const sex of selected)html+=chartTable(`${a.name} — ${sex} reference (correct repetitions)`,['Percentile',...labels],COURSE_PERCENTILES.map((p,i)=>[p+'th',...labels.map((_,j)=>rows[i][j*2+(sex==='female'?1:0)])]));note=a.id==='bench'?'Use the test load: male reference 80 lb, female reference 35 lb, including the bar; 60 metronome beats/min.':'Use the paced partial curl-up protocol: 40 beats/min, age-matched tape spacing, maximum 75 repetitions. Repeated values represent shared percentile anchors, not separate exact ranks.';source='Reference: Haff & Triplett (2016), Essentials of Strength Training and Conditioning, 4th edition.';}
 if(a.id==='situp'){for(const sex of selected)html+=chartTable(`1-minute full sit-up — ${sex} (correct repetitions)`,['Category','18–25','26–35','36–45','46–55','56–65','65+'],SITUP_CATEGORIES.map((name,i)=>[name,...SITUP_RANGES[sex][i]]));note='Use the full sit-up with anchored feet, 60-second limit, and assigned repetition cap. A capped count is not an uncapped maximum. Some boundaries have no automatic category; age 65 is not automatically classified.';source=SOURCES.situp.title;}
 if(a.id==='plank'){html=chartTable('Forearm plank — college-student reference (seconds)',['Percentile','Male reference (seconds)','Female reference (seconds)'],[10,20,30,40,50,60,70,80,90].map((p,i)=>[p+'th',PLANK_NORMS.male[i],PLANK_NORMS.female[i]]));note='Compare your hold time in seconds with the relevant column. The 50th percentile is the sample median, not an overall fitness rating. These values describe college students with a mean age near 20, tested to fatigue or technique failure. They are not age-specific norms for all adults. This lab stops at 360 seconds; reaching that cap does not establish your maximum hold time. No automatic category is assigned.';source='Strand et al. (2014), Norms for an Isometric Muscle Endurance Test, Table 2, Journal of Human Kinetics 40, 93–102. DOI: 10.2478/hukin-2014-0011';}
 if(a.id==='shoulder'){html=chartTable('Shoulder mobility reference — inches of fingertip overlap/gap',['Rating','Men: right up','Men: left up','Women: right up','Women: left up'],[['Excellent','>5','>4','>6','>5'],['Good','1–4','1–3','2–5','2–4'],['Fair','0','0','1','1'],['Low','<0','<0','<1','<1']]);note='Negative means a fingertip gap, zero means touching, positive means overlap. Compare each side separately using its best trial. 1 inch = 2.54 cm. Distances between the chart ranges receive no automatic rating.';source='Reference: ExRx shoulder mobility, Schoenfeld & Snarr (2021), and Howley & Thompson (2017).';}
 if(a.id==='sitreach'){source=SOURCES.ace.title;for(const sex of selected)html+=chartTable(`YMCA sit-and-reach — ${sex} (inches on the yardstick)`,['Percentile',...bandLabels.slice(0,5),'65+'],COURSE_PERCENTILES.map((p,i)=>[p+'th',...REACH_NORMS[sex].map(col=>col[i])]));note='Heels are at the 15-inch mark, not zero. Use the best of two trials. Divide a centimetre reading by 2.54 to compare with this inch scale. An automatic age-matched comparison is unavailable at age 65. Box/toes-at-zero readings are not equivalent.';}
 if(a.id==='ymca'){for(const sex of selected)html+=chartTable(`YMCA step recovery count — ${sex} (beats in one full minute)`,['Percentile',...bandLabels],STEP_PERCENTILES.map((p,i)=>[p+'th',...STEP_NORMS[sex].map(col=>col[i])]));note='These norms compare recovery pulse, not VO₂max. Lower pulse corresponds to higher reference percentiles. Use the 12-inch step, 96 beats/min, and full-minute recovery count.';source=SOURCES.ace.title;}
 if(a.id==='pushup'){const labels=['20–29','30–39','40–49','50–59','60–69'],ranges={male:[['≥36','≥30','≥25','≥21','≥18'],['29–35','20–29','17–24','13–20','11–17'],['22–28','17–21','13–16','10–12','8–10'],['17–21','12–16','10–12','7–9','5–7'],['≤16','≤11','≤9','≤6','≤4']],female:[['≥30','≥27','≥24','≥21','≥17'],['21–29','20–26','15–23','11–20','12–16'],['15–20','13–19','11–14','7–10','5–11'],['10–14','8–12','5–10','2–6','1–4'],['≤9','≤7','≤4','≤1','≤1']]},names=['Excellent','Very good','Good','Fair','Needs improvement'];for(const sex of selected)html+=chartTable(`Push-up — ${sex} reference (correct repetitions)`,['Category',...labels],names.map((n,i)=>[n,...ranges[sex][i]]));note='Male reference uses standard/toes push-ups; female reference uses modified/knees push-ups. An automatic category is unavailable for men aged 30–39 at 20–21 repetitions and women aged 60–69 at 1 repetition.';source='Reference: Haff & Triplett (2016), pp. 275, 303.';}
 if(a.id==='vertical'){source='Approximate classroom reference; reference population unspecified.';html=chartTable('Vertical jump — approximate reference (cm)',['Reference','Lower anchor','Typical anchor','Higher anchor'],[['Men','~50','~55','~60+'],['Women','~32','~36','~40+']]);note='These approximate examples support discussion, not an individual percentile or fitness classification.';}
 if(a.id==='broad'){html=chartTable('Standing broad jump — elite-athlete reference (cm)',['Percentile','Men','Women'],COURSE_PERCENTILES.map((p,i)=>[p+'th',[219,234,249,264,279,294,309,339,375][i],[189,204,219,234,249,264,279,293,315][i]]));note='This chart describes elite athletes, not an introductory student population. Use it to discuss reference-population differences; no elite-athlete classification is assigned automatically.';source='Reference: Haff & Triplett (2016), pp. 267, 300.';}
 if(!html)return '';
 return `<section aria-label="Norm reference chart"><h4>Norm Reference Chart</h4><p>${esc(note)}</p>${html}<details><summary>About this chart</summary><p>${esc(source)}</p></details><p class="hint">Reference labels describe a score in a particular table; they do not establish overall health or fitness. </p></section>`;
}
render(false);





