'use strict';
const KEY='exs101-fitness-assessment-v1';
const blank=()=>({courseRevision:1,version:1,meta:{},tests:{},synthesis:{},detective:'',compare:{},skipBody:false,view:'start',active:null,step:0});
let state=blank(),storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===1&&saved.meta&&saved.tests&&saved.synthesis){state={...blank(),...saved,courseRevision:saved.courseRevision??0};if(!ASSESSMENTS.some(a=>a.id===state.active))state.active=null;state.view='start';}}catch(e){storageOK=false;}
function migrateCourse(){if(state.courseRevision===1)return;for(const d of Object.values(state.tests)){d.complete=false;d.confirmed=false;d.values.notes=[d.values.notes,'Saved before the Canvas protocol update. Review the current procedure with your instructor before reusing these results.'].filter(Boolean).join(' ');}state.courseRevision=1;}
migrateCourse();
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v!==''&&v!=null&&Number.isFinite(Number(v))?Number(v):null;
const aById=id=>ASSESSMENTS.find(a=>a.id===id);
const data=id=>(state.tests[id]??={values:{},writing:{},confirmed:false,complete:false,include:true});
function save(announce=false){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;if(announce)$('#save-status').textContent='Progress saved on this device. It is not sent to your instructor.';}catch(e){storageOK=false;$('#save-status').textContent='Browser saving is unavailable. Keep this page open and download a progress backup before leaving.';}}
function field(key,label,value,type='text',opts={}){const id='field-'+key.replace(/[^a-zA-Z0-9]/g,'-');return `<div class="field"><label for="${id}">${esc(label)}</label>${type==='textarea'?`<textarea id="${id}" data-key="${esc(key)}">${esc(value)}</textarea>`:type==='select'?`<select id="${id}" data-key="${esc(key)}">${opts.options.map(([v,l])=>`<option value="${esc(v)}" ${String(value??'')===v?'selected':''}>${esc(l)}</option>`).join('')}</select>`:`<input id="${id}" data-key="${esc(key)}" type="${type}" value="${esc(value)}" ${type==='number'?`min="${opts.min??0}" max="${opts.max??10000}" step="${opts.step??'any'}"`:''}>`}${opts.hint?`<p class="hint">${esc(opts.hint)}</p>`:''}</div>`;}
function check(key,label,checked){return `<div class="field"><label><input type="checkbox" data-key="${esc(key)}" ${checked?'checked':''}>${esc(label)}</label></div>`;}
function sourceLink(key){const s=SOURCES[key];return s.url?`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.title)} (opens in a new tab)</a>`:esc(s.title);}
function errors(items){const el=$('#errors');el.innerHTML=items.length?`<div class="error" role="alert"><strong>Please check:</strong><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'';if(items.length){el.focus();}}
function metaErrors(){return ['student','group','date'].filter(k=>!state.meta[k]?.trim()).map(k=>({student:'Enter your student name.',group:'Enter your lab group/section.',date:'Enter the lab date.'}[k]));}
function ageBand(age){return age<18?null:age<=25?0:age<=35?1:age<=45?2:age<=55?3:age<=65?4:5;}
const bandLabels=['18–25','26–35','36–45','46–55','56–65','66+'];
function percentileBand(score,thresholds,percentiles,lowerBetter=false){
 const pairs=thresholds.map((t,i)=>[t,percentiles[i]]);let exact=pairs.filter(([t])=>Math.abs(score-t)<1e-8);
 if(exact.length)return exact.length===1?`At the published ${exact[0][1]}th percentile anchor`:`At shared published anchors: ${Math.min(...exact.map(x=>x[1]))}th–${Math.max(...exact.map(x=>x[1]))}th percentiles`;
 if(lowerBetter){if(score<pairs[0][0])return 'Beyond the highest published anchor (no exact percentile assigned)';if(score>pairs.at(-1)[0])return 'Beyond the lowest published anchor (no exact percentile assigned)';}
 else{if(score<pairs[0][0])return `Below the published ${pairs[0][1]}th percentile anchor`;if(score>pairs.at(-1)[0])return `Above the published ${pairs.at(-1)[1]}th percentile anchor`;}
 for(let i=1;i<pairs.length;i++)if(score>pairs[i-1][0]&&score<pairs[i][0])return `Between published ${Math.min(pairs[i-1][1],pairs[i][1])}th and ${Math.max(pairs[i-1][1],pairs[i][1])}th percentile anchors`;
 return 'No exact percentile assigned';
}
function best(v){const ns=['trial1','trial2','trial3'].map((k,i)=>({value:number(v[k]),trial:i+1})).filter(x=>x.value!==null);if(!ns.length)return null;const top=ns.reduce((best,x)=>x.value>best.value?x:best);return {...top,count:ns.length};}
function comparison(a,v){const sex=v.sex,age=number(v.age),b=ageBand(age??0),descriptive=reason=>({type:'descriptive',text:'Descriptive result — no normative classification assigned',reason});
 const course=courseComparison(a,v);if(course)return course;
 if(a.id==='rockport'){
  if(!['male','female'].includes(sex))return descriptive('The selected equation requires its original male/female reference variable. Without that variable, report the measured walking performance.');
  if(['weight','minutes','seconds','hr','age'].some(k=>number(v[k])===null))return {type:'pending',text:'Enter the measured variables to calculate the estimate.'};
  const time=Number(v.minutes)+Number(v.seconds)/60;
  if(age<18||age>69)return descriptive('The course equation age ranges are 18–29 and 30–69. No extrapolation is made.');
  const kg=Number(v.weight)*(v.weightUnit==='lb'?0.45359237:1);
  const value=age<30?88.768+8.892*(sex==='male'?1:0)-.2109*kg-1.4537*time-.1194*Number(v.hr):132.853-.1692*kg-.3877*age+6.315*(sex==='male'?1:0)-3.2649*time-.1565*Number(v.hr);
  if(value<=0)return descriptive('These inputs produce a non-positive estimate. Check the units, time, and heart rate; do not interpret this as a valid VO₂max.');
  return {type:'prediction',text:`Estimated VO₂max — not directly measured: ${value.toFixed(1)} mL/kg/min`,value,reason:vo2Context(value,v),equation:age<30?`88.768 + 8.892 × sex(1 male/0 female) − 0.2109 × mass(kg) − 1.4537 × time(decimal min) − 0.1194 × immediate finish HR. Mass: ${kg.toFixed(2)} kg; time: ${time.toFixed(3)} min.`:`132.853 − 0.1692 × mass(kg) − 0.3877 × age + 6.315 × sex(1 male/0 female) − 3.2649 × time(decimal min) − 0.1565 × HR(beats/min). Time used: ${time.toFixed(3)} min; mass used: ${kg.toFixed(2)} kg.`};
 }
 if(a.id==='queens'){
  if(!['male','female'].includes(sex)||v.cadence!==(sex==='male'?'24':'22'))return descriptive('No prediction is calculated because the reference variable/cadence does not match the selected equation. Record the pulse and performed protocol.');
  if(number(v.pulse)===null)return {type:'pending',text:'Enter the 15-second recovery pulse count.'};
  const hr=Number(v.pulse)*4,value=sex==='male'?111.33-.42*hr:65.81-.1847*hr;
  if(value<=0)return descriptive('These inputs produce a non-positive estimate. Check the pulse count and protocol before interpreting it.');
  return {type:'prediction',text:`Estimated VO₂max — not directly measured: ${value.toFixed(1)} mL/kg/min`,value,reason:vo2Context(value,v)+` Recovery pulse: ${v.pulse} beats in 15 seconds × 4 = ${hr} beats/min. This estimates VO₂max; it does not measure respiratory gases.`,equation:sex==='male'?'Male equation: 111.33 − 0.42 × recovery HR(beats/min).':'Female equation: 65.81 − 0.1847 × recovery HR(beats/min).'};
 }
 if(a.kind!=='norm')return descriptive(a.limit);
 if(!['male','female'].includes(sex))return descriptive('No reference category selected. The actual performance remains reportable.');
 if(a.id==='ymca'){
  if(b===null)return descriptive('The implemented reference table begins at age 18. No extrapolation is made.');
  if(number(v.hr)===null)return {type:'pending',text:'Record the full-minute recovery count.'};
  return {type:'norm',text:percentileBand(Number(v.hr),STEP_NORMS[sex][b],STEP_PERCENTILES,true),population:`YMCA adult ${sex} reference, age ${bandLabels[b]}; 12-inch step, 24 cycles/min, 3 minutes, full-minute recovery count.`,anchors:STEP_NORMS[sex][b],percentiles:STEP_PERCENTILES,unit:'recovery beats',reason:'Lower recovery counts correspond to higher published percentile anchors. No interpolation or extrapolation is used. Original reference-sample recruitment details are not supplied in this secondary summary.',source:'ace'};
 }
 if(a.id==='pushup'){
  if(age===null||age<20||age>=60)return descriptive('The implemented unambiguous age groups are 20–59. No classification is assigned outside these groups; the published 60–69 female ranges overlap.');
  if(v.version!==(sex==='male'?'standard':'modified'))return descriptive('The performed push-up version does not match this reference category. Repetitions remain descriptive.');
  if(number(v.reps)===null)return {type:'pending',text:'Record correctly completed repetitions.'};
  const i=Math.floor(age/10)-2,thresholds=PUSH_NORMS[sex][i],names=['Needs improvement','Fair','Good','Very good','Excellent'];let cat=0;thresholds.forEach(t=>{if(Number(v.reps)>=t)cat++;});
  return {type:'norm',text:`Published category: ${names[cat]}`,population:`CSEP (2003), reproduced by ACE: ${sex}, age ${20+i*10}–${29+i*10}, ${v.version} push-ups to fatigue.`,reason:'These are the source’s category names, not a judgment about the person or their overall health. Reference-sample recruitment details are not given in the ACE summary.',source:'ace',categories:names,thresholds};
 }
 if(a.id==='sitreach'){
  if(v.convention!=='ace15')return descriptive('This scale/zero point does not match the ACE yardstick reference. No conversion is used to imply that different protocols are equivalent.');
  if(b===null||age===65)return descriptive('No course comparison below age 18 or at the overlapping age-65 boundary.');
  const result=best({...v,trial3:''});if(!result)return {type:'pending',text:'Record at least one valid trial.'};
  if(result.count<2)return {type:'pending',text:'Record both valid trials for the selected sit-and-reach protocol.'};
  const inch=result.value/(v.unit==='cm'?2.54:1);
  return {type:'norm',text:percentileBand(inch,REACH_NORMS[sex][b],[10,20,30,40,50,60,70,80,90]),population:`YMCA adult ${sex} reference, age ${bandLabels[b]}; ACE yardstick, heels at 15 inches; best of two trials.`,anchors:REACH_NORMS[sex][b],percentiles:[10,20,30,40,50,60,70,80,90],unit:'inches on yardstick',reason:'Comparison uses the scale reading in inches. Body proportions affect performance; no exact percentile is interpolated.',source:'ace'};
 }
 if(a.id==='plank'){
  if(v.college!=='yes'||age===null||age<18||age>25)return descriptive('No comparison is assigned outside this app’s conservative college-age context (18–25). That eligibility window is an app choice, not a validated age cutoff from the study.');
  if(number(v.time)===null)return {type:'pending',text:'Record the hold time.'};
  return {type:'norm',text:percentileBand(Number(v.time),PLANK_NORMS[sex],[10,20,30,40,50,60,70,80,90]),population:`Strand et al. (2014): college students; ${sex} reference, mean age about 20; prone forearm plank to fatigue/technique failure.`,anchors:PLANK_NORMS[sex],percentiles:[10,20,30,40,50,60,70,80,90],unit:'seconds',reason:'These are sample percentile anchors, not age-specific standards for all adults. Table 2 contains inconsistent subgroup counts; this app uses only its sex-specific time anchors.',source:'plank'};
 }
 return descriptive(a.limit);
}
function rawResult(a,v){
 if(a.id==='rockport')return `1 mile: ${v.minutes??'—'} min ${v.seconds??'—'} s; finish HR ${v.hr??'—'} beats/min`;
 if(a.id==='ymca')return `${v.hr??'—'} beats counted in 60 seconds`;
 if(a.id==='queens')return `${v.pulse??'—'} beats in 15 seconds; ${number(v.pulse)!==null?Number(v.pulse)*4:'—'} beats/min; ${v.cadence??'—'} cycles/min`;
 if(a.id==='plank')return `${v.time??'—'} seconds${Number(v.time)===360?' (course cap reached; time to failure unknown)':''}`;
 if(['sitreach','vertical','broad'].includes(a.id)){const r=best(a.id==='sitreach'?{...v,trial3:''}:v);return r?`Best: ${r.value} ${v.unit} (trial ${r.trial}); ${r.count} valid trial${r.count===1?'':'s'} (${(a.id==='sitreach'?['trial1','trial2']:['trial1','trial2','trial3']).filter(k=>number(v[k])!==null).map(k=>`${v[k]} ${v.unit}`).join(', ')})`:'No trials recorded';}
 if(a.id==='shoulder'){const side=k=>{const vals=[1,2,3].map(i=>number(v[k+i])).filter(x=>x!==null);return vals.length?`${Math.max(...vals)} cm; trials: ${vals.join(', ')} cm`:'not recorded';};return `Right hand on top: ${side('right')}; left hand on top: ${side('left')} (negative = gap, positive = overlap)`;}
 if(a.id==='bia')return `Estimated body fat: ${v.fat??'—'}%; device: ${v.device??'—'}`;
 if(a.id==='fit3d')return `${v.output==='fat'?'Estimated body fat':v.label||'Selected output'}: ${v.value??'—'} ${v.output==='fat'?'%':v.unit||''}; ${v.method||'method not selected'}; ${v.device||'device not recorded'}`;
 return `${v.reps??'—'} correct repetitions${a.id==='bench'?`; load: ${v.load==='other'?v.loadOther:(v.load||'—')+' lb'}`:''}${a.id==='pushup'?`; ${v.version||'version not selected'}`:''}${a.id==='squat'&&v.adaptation?`; adaptation: ${v.adaptation}`:''}`;
}
function assessmentErrors(a,d,writing=true){const out=[],v=d.values;
 for(const f of a.fields){const value=v[f.key],ns=number(value);if(a.required.includes(f.key)&&(value==null||String(value).trim()===''))out.push(`Enter ${f.label}.`);
  if(f.type==='number'&&value!=null&&value!==''&&(ns===null||ns<f.min||ns>f.max||(f.step===1&&!Number.isInteger(ns))))out.push(`${f.label}: enter ${f.step===1?'a whole number':'a number'} from ${f.min} to ${f.max}.`);
 }
 if(!d.confirmed)out.push('Confirm that you followed the recorded protocol.');
 if(a.id==='vertical'&&['trial1','trial2','trial3'].some(k=>number(v[k])===null))out.push('Record all three valid vertical jump trials.');
 if(a.id==='sitreach'&&v.convention==='box'&&!v.box?.trim())out.push('Describe your box/zero-point convention.');
 if(a.id==='sitreach'&&v.convention!=='toes0'&&['trial1','trial2','trial3'].some(k=>number(v[k])!==null&&number(v[k])<0))out.push('Negative readings are available only for the toes-at-zero convention.');
 if(a.id==='rockport'&&number(v.minutes)===0&&number(v.seconds)===0)out.push('Walking time must be greater than zero.');
 if(a.id==='bench'&&v.load==='other'&&!v.loadOther?.trim())out.push('Record the other load and units.');
 if(a.id==='fit3d'){if(v.output==='other'&&(!v.label?.trim()||!v.unit?.trim()))out.push('Name the selected output and its units.');if(v.output==='fat'&&(number(v.value)>100||v.method!=='estimate'))out.push('Body-fat percentage must be 0–100 and identified as a modeled estimate.');}
 const c=reportComparison(a,d);if(c.type==='pending')out.push(c.text);
 if(writing){if(!d.writing.suggest?.trim())out.push('Explain what this result suggests.');if(!d.writing.limit?.trim())out.push('Explain what this assessment cannot establish.');if(a.extra&&!d.writing.extra?.trim())out.push('Complete the assessment comparison/reflection prompt.');if(c.type==='norm'&&!state.detective.trim())out.push('Complete “Before You Use the Norm.”');}
 return [...new Set(out)];
}
const completed=()=>ASSESSMENTS.filter(a=>state.tests[a.id]?.complete&&!assessmentErrors(a,state.tests[a.id]).length);
function progress(){const counts=Object.fromEntries(Object.keys(GROUPS).map(g=>[g,completed().filter(a=>a.group===g).length]));const base=Object.entries(GROUPS).reduce((s,[g,v])=>s+Math.min(v.need,counts[g]),0);const extra=Object.entries(GROUPS).reduce((s,[g,v])=>s+(v.need?Math.max(0,counts[g]-v.need):0),0);return {counts,base,extra,credit:base+Math.min(1,extra),ready:base===5&&extra>=1};}
function toolbar(){return `<div class="toolbar"><button class="secondary" data-action="dashboard">Assessment Dashboard</button><div class="actions"><button class="secondary" data-action="save">Save Progress</button><button class="secondary" data-action="backup">Download Progress Backup</button><button class="secondary" data-action="reset">Start Over</button></div></div><p class="hint">Progress saves automatically. Your saved progress remains on this device. It is not sent to your instructor. Clear it after using a shared device.</p>`;}
function start(){return `<section class="panel"><h2 tabindex="-1">Prepare Your Lab</h2><p>This is a digital laboratory notebook and report builder. Enter actual assessment results collected during class.</p><div class="note"><h3>Your Data &amp; Privacy</h3><p>Your assessment data are stored on this device while you complete the lab. Your instructor does not receive your results through this website. You choose what is submitted when you upload your completed Assessment Profile PDF to Canvas.</p><p>No account or medical information is needed. Browser settings and Canvas embeds can affect local saving; a progress backup is available.</p></div><div class="grid">${field('meta.student','Student name',state.meta.student)}${field('meta.group','Lab group/section',state.meta.group)}${field('meta.date','Date',state.meta.date,'date')}</div><p>Use assessments approved by your instructor, follow station safety directions, and allow recovery between tests. Stop for pain, dizziness, or loss of control and tell your instructor. Ask for an alternative when an assessment is unsuitable.</p><p><strong>Required:</strong> 1 cardiorespiratory + 2 muscular endurance + 1 flexibility + 1 power + 1 additional assessment = 6 distinct assessments.</p><p><strong>Body Composition — Optional.</strong> You may complete it if available and you choose to participate. You may also skip it. No explanation is required.</p><div class="actions"><button data-action="begin">${Object.keys(state.tests).length?'Continue My Lab':'Open Assessment Dashboard'}</button><button class="secondary" data-action="import">Restore Progress Backup</button></div><input type="file" id="import-file" accept="application/json,.json" hidden></section>`;}
function dashboard(){const p=progress();return `<section class="panel"><h2 tabindex="-1">Assessment Dashboard</h2><p>${p.ready?'<strong>Required Assessments Complete</strong>':`<strong>${p.credit} of 6 required assessments completed</strong>`}</p><progress max="6" value="${p.credit}" aria-label="Required assessment progress">${p.credit} of 6</progress><p class="hint">Completion includes recording your result, interpretation, and limitation. More assessments do not produce a better fitness score.</p><div class="grid">${Object.entries(GROUPS).filter(([g])=>g!=='body').map(([g,group])=>`<section class="panel category"><h3>${group.name}</h3><p class="badge">${Math.min(group.need,p.counts[g])} of ${group.need} complete${p.counts[g]>group.need?`; ${p.counts[g]-group.need} additional` :''}</p>${ASSESSMENTS.filter(a=>a.group===g).map(a=>`<button class="secondary" data-assessment="${a.id}">${a.name} — ${state.tests[a.id]?.complete&&!assessmentErrors(a,state.tests[a.id]).length?'✓ Complete':state.tests[a.id]?'Draft':'Start'}</button>`).join('')}</section>`).join('')}<section class="panel category"><h3>Additional Assessment</h3><p class="badge">${Math.min(1,p.extra)} of 1 complete</p><p>Complete another distinct assessment from any required category. One assessment cannot fill two slots. Body composition does not count toward this requirement.</p></section><section class="panel category"><h3>Body Composition — Optional</h3><p>You may participate if available or skip this section. No explanation is required.</p>${state.skipBody?'<p>Skipped — optional.</p><button class="secondary" data-action="show-body">Show Optional Assessments</button>':ASSESSMENTS.filter(a=>a.group==='body').map(a=>`<button class="secondary" data-assessment="${a.id}">${a.name} — ${state.tests[a.id]?.complete?'Recorded':state.tests[a.id]?'Draft':'Start'}</button>`).join('')+'<button class="secondary" data-action="skip-body">Skip Body Composition</button>'}</section></div><h3>My Assessment Profile</h3>${completed().length?`<ul>${completed().map(a=>`<li>✓ ${a.name} — ${GROUPS[a.group].name}: result recorded</li>`).join('')}</ul>`:'<p>Your completed assessments will appear here.</p>'}<div class="actions"><button data-action="synthesis" ${p.ready?'':'disabled'}>Looking Across Your Assessments</button><button class="secondary" data-action="info">Edit Lab Information</button></div>${!p.ready?'<p class="hint">Complete every required category and one additional assessment to unlock synthesis.</p>':''}</section>`;}
function assessment(){const a=aById(state.active),d=data(a.id),s=state.step;
 const steps=['Prepare','Record','Interpret'];return `<section class="panel"><h2 tabindex="-1">${a.name}</h2><p>${GROUPS[a.group].name}</p><nav class="steps" aria-label="Assessment steps">${steps.map((name,i)=>`<button data-step="${i}" aria-current="${i===s?'step':'false'}">${i+1}. ${name}</button>`).join('')}</nav>${s===0?prepareAssessment(a,d):s===1?recordAssessment(a,d):interpretAssessment(a,d)}<div class="actions">${s>0?`<button class="secondary" data-step="${s-1}">Back</button>`:''}${s<2?`<button data-step="${s+1}">Continue to ${steps[s+1]}</button>`:`<button data-action="complete">Save Completed Assessment</button>`}<button class="secondary" data-action="dashboard">Save Draft &amp; Return to Dashboard</button></div></section>`;
}
function prepareAssessment(a,d){return `<h3>1. What Does This Measure?</h3><p>${a.measure}</p><h3>2. How Does the Test Work?</h3><p>${a.protocol}</p><details><summary>View Protocol / Learn More</summary><ul>${a.sources.map(k=>`<li>${sourceLink(k)}</li>`).join('')}</ul></details>${a.check?`<h3>3. Protocol Check — Practice Only</h3>${field('practice',a.check[0],d.practice,'select',{options:[['','Choose an answer'],...a.check[1].map((t,i)=>[String(i),t])]})}<p id="check-feedback" class="check-feedback" role="status">${practiceFeedback(a,d.practice)}</p>`:''}<p class="note">${a.perform}</p><p class="hint">If your instructor uses a modified protocol, do not treat the reference comparison as protocol-matched. Record the change and use descriptive interpretation.</p>`;}
function practiceFeedback(a,v){if(!a.check||v==null||v==='')return '';return Number(v)===a.check[2]?'Correct. Use this timing/protocol while testing.':'Review “How Does the Test Work?” and try again. This check is not graded.';}
function recordAssessment(a,d){return `<h3>4. Perform the Assessment</h3><p class="note">${a.perform}</p><h3>5. Record Your Result</h3><p>Enter the actual result. Units appear beside each measurement. Blank optional trial fields are not treated as zero.</p><div class="grid">${a.fields.map(f=>field('values.'+f.key,f.label,d.values[f.key],f.type,f)).join('')}</div>${field('values.notes','Protocol change / testing note — optional (no medical information)',d.values.notes,'textarea')}${check('confirmed','I followed the recorded protocol; any change is described above.',d.confirmed)}${a.group==='body'?check('include','Include this optional assessment in my report',d.include!==false):''}<p class="hint">Reference categories reproduce variables used by older sources; they are not a statement about identity. You can choose a descriptive result. No equation is calculated without its required source variable.</p><div id="record-result" class="result" role="status" aria-live="polite">${esc(rawResult(a,d.values))}</div>`;}
function detective(){return `<section class="note"><h3>Before You Use the Norm</h3><p>A comparison needs four checks: <strong>Who was measured?</strong> The reference population. <strong>How?</strong> The protocol. <strong>How is it organized?</strong> Age, reference sex, percentile or category. <strong>Does the protocol match yours?</strong></p>${field('detective',"Why can’t we use any push-up norm chart we find online to interpret your push-up score?",state.detective,'textarea')}</section>`;}
function normDetails(c){return `<details><summary>Where did these norms come from?</summary><p>${esc(c.population)}</p><p>${esc(c.reason)}</p><p>${sourceLink(c.source)}</p>${c.anchors?`<div class="scroll"><table class="norm-data"><caption>Published reference anchors (${esc(c.unit)})</caption><thead><tr><th scope="col">Percentile anchor</th><th scope="col">Reference result</th></tr></thead><tbody>${c.anchors.map((x,i)=>`<tr><th scope="row">${c.percentiles[i]}th</th><td>${x}</td></tr>`).join('')}</tbody></table></div>`:''}${c.categories?`<p>Category minimum repetitions for this group:</p><ul>${c.categories.map((name,i)=>`<li>${esc(name)}: ${i===0?'below '+c.thresholds[0]:c.thresholds[i-1]+' or more (up to the next category)'}</li>`).join('')}</ul>`:''}<p>Normative data describe a comparison with a particular population and protocol. They are not universal definitions of health, fitness, or athletic ability.</p></details>`;}
function interpretAssessment(a,d){const c=d.values.notes?.trim()?{type:'descriptive',text:'Descriptive result — no normative classification assigned',reason:'A protocol change/testing note is recorded. Review it with your instructor; automated reference/prediction use is withheld.'}:comparison(a,d.values);return `<h3>Your Result</h3><p class="result">${esc(rawResult(a,d.values))}</p><h3>6. Reference Comparison</h3><p><strong>${esc(c.text)}</strong></p>${c.reason?`<p>${esc(c.reason)}</p>`:''}${c.equation?`<details><summary>Prediction equation and source</summary><p>${esc(c.equation)}</p><ul>${a.sources.map(k=>`<li>${sourceLink(k)}</li>`).join('')}</ul></details>`:''}${c.type==='norm'?`${!state.detective.trim()?detective():''}${normDetails(c)}`:''}<p class="hint">${a.limit}</p><h3>7. Interpret</h3>${field('writing.suggest','What does this result suggest?',d.writing.suggest,'textarea')}<h3>8. Limit</h3>${field('writing.limit','What can this assessment NOT establish?',d.writing.limit,'textarea')}${a.extra?field('writing.extra',a.extra,d.writing.extra,'textarea'):''}`;}
function reportComparison(a,d){return d.values.notes?.trim()?{type:'descriptive',text:'Descriptive result — no normative classification assigned',reason:'Protocol change/testing note recorded; automatic comparison or prediction withheld.'}:comparison(a,d.values);}
function synthesisPrompts(){const list=completed().filter(a=>a.group!=='body'||data(a.id).include!==false),norm=list.some(a=>reportComparison(a,data(a.id)).type==='norm'),estimate=list.some(a=>['prediction','estimate'].includes(reportComparison(a,data(a.id)).type)||a.id==='bia'||(a.id==='fit3d'&&data(a.id).values.method==='estimate'));return [
 'Choose two assessments that provided very different kinds of information. What did each measure?',
 norm?'Choose one normative comparison from today’s lab. What does that comparison allow you to conclude? What does it NOT allow you to conclude?':'Your selected results do not include a normative comparison. Choose one result: what protocol and reference-population information would you need before assigning one? What would that comparison still NOT establish?',
 estimate?'Identify one value from today’s lab that was estimated rather than directly measured. How was the estimate produced, and why does the distinction between measurement and estimation matter?':'Your selected tests did not produce a prediction-equation/body-composition estimate. Choose one directly recorded result. How would estimating VO₂max from field performance differ from measuring respiratory gases, and why does that distinction matter?',
 'Someone looks at all these results and asks, “So, am I fit?” Why is that question harder to answer than it sounds?'
 ];}
function methodsIncluded(){return completed().some(a=>a.id==='bia'&&data(a.id).include!==false)&&completed().some(a=>a.id==='fit3d'&&data(a.id).include!==false);}
function comparisonPrompts(){return ['Were the results identical? If the outputs have different units or describe different characteristics, can they be compared directly?','Why might two methods assessing the same person produce different estimates?','Does a difference automatically mean one method is “wrong”? Explain.'];}
function synthesis(){return `<section class="panel"><h2 tabindex="-1">Looking Across Your Assessments</h2><p>A test gives evidence about a specific characteristic. It does not define the person. Write your own conclusions using the results you collected.</p>${synthesisPrompts().map((q,i)=>field('synthesis.q'+i,`${i+1}. ${q}`,state.synthesis['q'+i],'textarea')).join('')}${methodsIncluded()?`<h3>Compare the Methods</h3><p>${esc(rawResult(aById('bia'),data('bia').values))}</p><p>${esc(rawResult(aById('fit3d'),data('fit3d').values))}</p>${comparisonPrompts().map((q,i)=>field('compare.q'+i,q,state.compare['q'+i],'textarea')).join('')}`:''}<div class="actions"><button data-action="review" ${reportMissing().length?'disabled':''}>Generate My Assessment Profile</button><button class="secondary" data-action="dashboard">Return to Dashboard</button></div><p id="report-readiness" class="hint">${reportMissing().length?'Complete the four synthesis responses'+(methodsIncluded()?' and method comparison':'')+' to generate your profile.':'Your profile is ready to review.'}</p></section>`;}
function reportMissing(){const out=[...metaErrors()];if(!progress().ready)out.push('Complete every required assessment category and an additional assessment.');synthesisPrompts().forEach((q,i)=>{if(!state.synthesis['q'+i]?.trim())out.push(`Complete synthesis response ${i+1}.`);});if(methodsIncluded())comparisonPrompts().forEach((q,i)=>{if(!state.compare['q'+i]?.trim())out.push(`Complete method comparison ${i+1}.`);});return out;}
function reportBlocks(){const list=completed().filter(a=>a.group!=='body'||data(a.id).include!==false),blocks=[{tag:'H1',text:'EXS101 Fitness Assessment Lab'},{tag:'H2',text:'Assessment Profile'},{tag:'P',text:`Student: ${state.meta.student}\nDate: ${state.meta.date}\nLab group/section: ${state.meta.group}`},{tag:'H2',text:'Assessments Completed'}];
 for(const a of list){const d=data(a.id),c=reportComparison(a,d);blocks.push({tag:'H3',text:a.name},{tag:'P',text:`Fitness component: ${GROUPS[a.group].name}\nResult: ${rawResult(a,d.values)}\n${c.text}${c.population?'\nReference group: '+c.population:''}`});}
 blocks.push({tag:'H2',text:'Individual Assessment Interpretation'});
 for(const a of list){const d=data(a.id),c=reportComparison(a,d);blocks.push({tag:'H3',text:a.name},{tag:'P',text:`What was measured: ${a.measure}`},{tag:'P',text:`How it was measured: ${a.protocol}`},{tag:'P',text:`Result: ${rawResult(a,d.values)}`});
 const vals=a.fields.filter(f=>d.values[f.key]!=null&&d.values[f.key]!=='').map(f=>{let val=d.values[f.key];if(f.type==='select')val=f.options.find(o=>o[0]===val)?.[1]||val;return `${f.label}: ${val}`;});blocks.push({tag:'P',text:'Recorded variables:\n'+vals.join('\n')});
 blocks.push({tag:'P',text:`Reference comparison: ${c.text}\n${c.population||''}\n${c.reason||''}${c.equation?'\nEquation: '+c.equation:''}`});if(d.values.notes)blocks.push({tag:'P',text:'Protocol/testing note: '+d.values.notes});blocks.push({tag:'P',text:'What the result suggests:\n'+d.writing.suggest},{tag:'P',text:'What the assessment cannot establish:\n'+d.writing.limit});if(a.extra)blocks.push({tag:'P',text:a.extra+'\n'+d.writing.extra});blocks.push({tag:'P',text:'Sources: '+a.sources.map(k=>SOURCES[k].title).join(' | ')});}
 if(list.some(a=>reportComparison(a,data(a.id)).type==='norm'))blocks.push({tag:'H2',text:'Before You Use the Norm'},{tag:'P',text:'Why can’t we use any push-up norm chart we find online?\n'+state.detective});
 blocks.push({tag:'H2',text:'Looking Across My Assessments'});synthesisPrompts().forEach((q,i)=>blocks.push({tag:'H3',text:`${i+1}. ${q}`},{tag:'P',text:state.synthesis['q'+i]}));
 if(methodsIncluded()){blocks.push({tag:'H2',text:'Compare the Methods'},{tag:'P',text:rawResult(aById('bia'),data('bia').values)+'\n'+rawResult(aById('fit3d'),data('fit3d').values)});comparisonPrompts().forEach((q,i)=>blocks.push({tag:'H3',text:q},{tag:'P',text:state.compare['q'+i]}));}
 blocks.push({tag:'H2',text:'Sources'});const used=[...new Set(list.flatMap(a=>a.sources))];for(const k of used)blocks.push({tag:'P',text:SOURCES[k].title+(SOURCES[k].url?'\n'+SOURCES[k].url:'')});
 blocks.push({tag:'P',text:'This report was assembled from assessment data and responses entered by the student using the EXS101 Fitness Assessment Lab.'});return blocks;
}
function reportHTML(standalone=false){return reportBlocks().map(b=>{const tag=(standalone?{H1:'h1',H2:'h2',H3:'h3',P:'p'}:{H1:'h2',H2:'h3',H3:'h4',P:'p'})[b.tag];return `<${tag}>${esc(b.text)}</${tag}>`;}).join('');}
function report(){return `<section class="panel"><h2 tabindex="-1">Review Your Assessment Profile</h2><p>Review your results and your own responses before downloading. You can return to any assessment to revise it.</p><div class="actions"><button data-action="pdf">Download PDF</button><button class="secondary" data-action="html">Download Accessible HTML Copy</button><button class="secondary" data-action="synthesis">Edit Synthesis</button></div><h3>Submit Your Lab</h3><ol><li>Review your Assessment Profile.</li><li>Select <strong>Download PDF</strong>.</li><li>Save the PDF to your device.</li><li>Return to Canvas.</li><li>Upload the PDF to the Fitness Assessment Lab assignment.</li></ol><p>This website does not submit to Canvas.</p><details><summary>Optional body-composition report choices</summary><p>Optional results are included only when selected. You may exclude them without explanation.</p>${completed().filter(a=>a.group==='body').map(a=>check('include-'+a.id,'Include '+a.name,data(a.id).include!==false)).join('')||'<p>No optional results selected.</p>'}</details><article class="report">${reportHTML()}</article></section>`;}
function setValue(key,value){if(key.startsWith('include-')){data(key.slice(8)).include=value;save();render();return;}
 if(key.startsWith('meta.'))state.meta[key.slice(5)]=value;
 else if(key.startsWith('synthesis.'))state.synthesis[key.slice(10)]=value;
 else if(key.startsWith('compare.'))state.compare[key.slice(8)]=value;
 else if(key==='detective')state.detective=value;
 else{const d=data(state.active);if(key.startsWith('values.')){d.values[key.slice(7)]=value;d.complete=false;}else if(key.startsWith('writing.')){d.writing[key.slice(8)]=value;d.complete=false;}else{d[key]=value;if(key==='confirmed')d.complete=false;}}
 save();
 if(key==='practice')$('#check-feedback').textContent=practiceFeedback(aById(state.active),value);
 if(state.view==='assessment'&&state.step===1&&$('#record-result'))$('#record-result').textContent=rawResult(aById(state.active),data(state.active).values);
 if(state.view==='synthesis'){const ready=!reportMissing().length;const btn=$('[data-action=review]');btn.disabled=!ready;$('#report-readiness').textContent=ready?'Your profile is ready to review.':'Complete the synthesis responses'+(methodsIncluded()?' and method comparison':'')+' to generate your profile.';}
}
function render(focus=true){if(state.view==='assessment'&&!state.active)state.view='dashboard';if(['synthesis','report'].includes(state.view)&&!progress().ready)state.view='dashboard';
 $('#app').innerHTML=`${state.view==='start'?'':toolbar()}<div id="errors" tabindex="-1"></div>${state.view==='start'?start():state.view==='dashboard'?dashboard():state.view==='assessment'?assessment():state.view==='synthesis'?synthesis():report()}`;
 $('#app').querySelectorAll('[data-key]').forEach(el=>el.addEventListener(el.type==='checkbox'||el.tagName==='SELECT'?'change':'input',()=>setValue(el.dataset.key,el.type==='checkbox'?el.checked:el.value)));
 $('#app').querySelectorAll('[data-assessment]').forEach(el=>el.onclick=()=>{state.active=el.dataset.assessment;data(state.active);state.view='assessment';state.step=0;save();render();});
 $('#app').querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>{state.step=Number(el.dataset.step);save();render();});
 $('#app').querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action));
 if($('#import-file'))$('#import-file').onchange=restore;
 if(focus){const h=$('#app h2');if(h){h.focus();h.scrollIntoView({block:'start'});}}
 if(!storageOK)$('#save-status').textContent='Browser saving is unavailable. Keep this page open and download a progress backup before leaving.';
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(ext){return 'EXS101-Assessment-Profile-'+(state.meta.student||'Student').replace(/[^a-z0-9_-]/gi,'-')+'.'+ext;}
function action(which){
 if(which==='begin'){const e=metaErrors();errors(e);if(e.length)return;state.view='dashboard';}
 if(which==='dashboard')state.view='dashboard';
 if(which==='info')state.view='start';
 if(which==='save'){save(true);return;}
 if(which==='reset'){if(!confirm('Start over and remove all saved assessment data and responses from this device?'))return;try{localStorage.removeItem(KEY);}catch(e){}state=blank();render();$('#save-status').textContent='Saved assessment data cleared from this device.';return;}
 if(which==='skip-body'){state.skipBody=true;for(const a of ASSESSMENTS.filter(a=>a.group==='body'))if(state.tests[a.id])state.tests[a.id].include=false;state.view='dashboard';}
 if(which==='show-body'){state.skipBody=false;}
 if(which==='synthesis'){if(!progress().ready)return;state.view='synthesis';}
 if(which==='complete'){const a=aById(state.active),d=data(a.id),e=assessmentErrors(a,d);errors(e);if(e.length)return;d.complete=true;state.view='dashboard';}
 if(which==='review'){const e=reportMissing();errors(e);if(e.length)return;state.view='report';}
 if(which==='pdf'){const e=reportMissing();errors(e);if(e.length)return;try{download(makeProfilePDF(reportBlocks(),state.meta),filename('pdf'));$('#save-status').textContent='PDF generated. Review and save it, then upload it to Canvas.';}catch(e){errors(['PDF generation failed. Your draft remains here. Download the accessible HTML copy or try again.']);}return;}
 if(which==='html'){const e=reportMissing();errors(e);if(e.length)return;download(new Blob([`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EXS101 Assessment Profile</title><style>body{font:17px/1.55 Arial,sans-serif;color:#1f2937;max-width:850px;padding:24px;margin:auto}p{white-space:pre-wrap;overflow-wrap:anywhere}h1,h2,h3,h4{color:#005450}</style></head><body><main>${reportHTML(true)}</main></body></html>`],{type:'text/html'}),filename('html'));return;}
 if(which==='backup'){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'EXS101-Fitness-Progress.json');$('#save-status').textContent='Progress backup downloaded. It contains your entered assessment data; keep it private.';return;}
 if(which==='import'){$('#import-file').click();return;}
 save();render();
}
async function restore(event){const file=event.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('too large');const s=JSON.parse(await file.text());if(s.version!==1||!s.meta||!s.tests||!s.synthesis)throw Error('invalid');for(const a of ASSESSMENTS){const d=s.tests[a.id];if(d&&(!d.values||!d.writing))throw Error('invalid');}if(!confirm('Replace the current draft with this progress backup?'))return;state={...blank(),...s,courseRevision:s.courseRevision??0,view:'start',active:null};migrateCourse();save();render();$('#save-status').textContent='Progress restored. Check your lab information and continue.';}catch(e){errors(['This file is not a valid EXS101 Fitness Assessment Lab progress backup.']);}}
function vo2Context(value,v){const age=number(v.age);if(age===null||age<20||age>69)return 'Estimated, not directly measured. The supplied VO₂max table covers ages 20–69; no age-matched comparison is available.';return 'Estimated, not directly measured. Course VO₂max reference ('+v.sex+', age '+(Math.floor(age/10)*10)+'–'+(Math.floor(age/10)*10+9)+'): '+percentileBand(value,COURSE_VO2[v.sex][Math.floor(age/10)-2],COURSE_VO2_PERCENTILES)+'. The course table cites ACSM/NSCA and a secondary summary; sample recruitment is not supplied. No exact percentile is interpolated.';}
function courseComparison(a,v){const sex=v.sex,age=number(v.age),desc=reason=>({type:'descriptive',text:'Descriptive result — no normative classification assigned',reason});
 if(a.id==='pushup'){
  if(!['male','female'].includes(sex)||age===null||age<20||age>69||v.version!==(sex==='male'?'standard':'modified'))return desc('The course reference requires ages 20–69 and a matched version/reference category.');
  const score=number(v.reps);if(score===null)return {type:'pending',text:'Record correct repetitions.'};
  const i=Math.floor(age/10)-2;
  if((sex==='male'&&i===1&&score>=20&&score<=21)||(sex==='female'&&i===4&&score===1))return desc('This score falls in overlapping course categories. Confirm the table with your instructor; no category is selected.');
  const tables={male:[[17,22,29,36],[12,17,20,30],[10,13,17,25],[7,10,13,21],[5,8,11,18]],female:[[10,15,21,30],[8,13,20,27],[5,11,15,24],[2,7,11,21],[1,5,12,17]]},thresholds=tables[sex][i],categories=['Needs improvement','Fair','Good','Very good','Excellent'];let index=0;thresholds.forEach(t=>{if(score>=t)index++;});return {type:'norm',text:'Published category: '+categories[index],population:`Course ${sex} reference, ages ${20+i*10}–${29+i*10}, ${v.version} push-ups.`,reason:'Source category labels describe this assessment, not overall health. Ambiguous overlapping scores are withheld.',source:'courseNSCA',categories,thresholds};
 }
 if(!['bench','curlup'].includes(a.id))return null;
 if(!['male','female'].includes(sex))return desc('No reference category selected. Performance remains reportable.');
 if(age===null||age<(a.id==='bench'?18:20)||(a.id==='curlup'&&age>69))return desc('Age is outside the supplied table. No extrapolation is made.');
 if(a.id==='bench'&&v.load!==(sex==='male'?'80':'35'))return desc('Performed load does not match this course reference category.');
 const score=number(v.reps);if(score===null)return {type:'pending',text:'Record correct repetitions.'};
 const b=a.id==='bench'?ageBand(age):Math.floor(age/10)-2,anchors=(a.id==='bench'?COURSE_BENCH_ROWS:COURSE_CURL_ROWS).map(row=>row[b*2+(sex==='female'?1:0)]);
 return {type:'norm',text:percentileBand(score,anchors,COURSE_PERCENTILES),population:`Course ${a.name}, ${sex} reference, age ${a.id==='bench'?bandLabels[b]:20+b*10+'–'+(29+b*10)}; ${a.id==='bench'?v.load+' lb, 60 beats/min':'age-matched marker spacing, 40 beats/min, maximum 75'}.`,anchors,percentiles:COURSE_PERCENTILES,unit:'correct repetitions',source:'courseNSCA',reason:'Course-supplied percentile anchors; sample recruitment details are not provided. Shared anchors and test ceilings do not imply an exact individual rank.'};
}
render(false);

