'use strict';
const SOURCES={
 ace:{title:'ACE Group Fitness Instructor Fitness Assessment Protocols; YMCA Fitness Testing and Assessment Manual (4th ed., 2000), Tables 1–2 and 18; CSEP CPAFLA (3rd ed., 2003), Table 3.',url:'https://www.acefitness.org/groupfitnessresources/pdfs/GFI_Assessments.pdf'},
 rockport:{title:'Kline et al. (1987), Estimation of VO₂max from a one-mile track walk, gender, age, and body weight.',url:'https://pubmed.ncbi.nlm.nih.gov/3600239/'},
 rockEquation:{title:'University of Michigan Exercise Physiology: Predict VO₂max using the Rockport Walking Test (relative equation).',url:'https://websites.umich.edu/~exphysio/mvs.241/Assig4.Pred.VOmax.pdf'},
 phenxWalk:{title:'PhenX Toolkit protocol 150101: One Mile Walk; heart rate measured during final 10 seconds.',url:'https://www.phenxtoolkit.org/protocols/view/150101'},
 phenx:{title:'PhenX Toolkit protocol 150201: Integrated Fitness; YMCA one-minute Half Sit-Up.',url:'https://www.phenxtoolkit.org/protocols/view/150201'},
 queens:{title:'Queens College Step Test Protocol, Uttar Pradesh University of Medical Sciences.',url:'https://api.upums.ac.in/pdfs/doc-1741758081909-174288715.pdf'},
 queensStudy:{title:'Different consecutive training protocols to design an intervention program for overweight youth (2017); Queens College protocol and equations.',url:'https://www.dovepress.com/different-consecutive-training-protocols-to-design-an-intervention-pro-peer-reviewed-fulltext-article-DMSO'},
 plank:{title:'Strand et al. (2014), Norms for an Isometric Muscle Endurance Test, Table 2. Journal of Human Kinetics, 40, 93–102.',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4096102/'},
 bench:{title:'ACSM’s Health-Related Physical Fitness Assessment Manual: YMCA submaximal bench-press protocol (course protocol; no reference table implemented).',url:'https://acsm.org/education-resources/books/'},
 jump:{title:'NSCA: Revisiting the Vertical Jump—Managing the Relationship between Power and Skill.',url:'https://www.nsca.com/education/videos/revisiting-the-vertical-jump/'},
 bia:{title:'NIH Technology Assessment Conference Statement (1996): Bioelectrical impedance analysis in body composition measurement.',url:'https://pubmed.ncbi.nlm.nih.gov/8780375/'},
 fit3d:{title:'Fit3D Body Fat FAQ: anthropometric measurements and DXA-derived prediction models.',url:'https://service.fit3d.com/knowledge/fit3d-body-fat-faq-1'},
 class:{title:'EXS101 classroom recording protocol. Descriptive performance only; no population norms selected.',url:null}
};
const GROUPS={cardio:{name:'Cardiorespiratory Fitness',need:1},endurance:{name:'Muscular Endurance',need:2},flexibility:{name:'Flexibility',need:1},power:{name:'Power',need:1},body:{name:'Body Composition — Optional',need:0}};
const n=(key,label,min=0,max=10000,step='any')=>({key,label,type:'number',min,max,step});
const choice=(key,label,options)=>({key,label,type:'select',options});
const txt=(key,label)=>({key,label,type:'text'});
const sex=()=>choice('sex','Reference category used by this source',[['','Select a reference category'],['male','Male reference'],['female','Female reference'],['none','No reference comparison / equation']]);
const age=()=>n('age','Age (years)',1,120,1);
const trials=(label,max=1000)=>[n('trial1',`Trial 1 ${label}`,0,max),n('trial2',`Trial 2 ${label} — optional`,0,max),n('trial3',`Trial 3 ${label} — optional`,0,max)];
const ASSESSMENTS=[
{id:'rockport',name:'Rockport 1-Mile Walk',group:'cardio',measure:'Cardiorespiratory fitness estimated from a submaximal walking assessment.',kind:'prediction',sources:['rockport','rockEquation','phenxWalk'],protocol:'Walk a measured, level mile as briskly as possible without running. Record minutes and seconds. Use a heart-rate monitor to record heart rate during the final 10 seconds of the walk; do not substitute a delayed recovery pulse.',perform:'Measured mile · walk throughout · stopwatch · heart-rate monitor. Your instructor manages screening, testing, and cool-down.',fields:[age(),sex(),n('weight','Body mass',1,1500),choice('weightUnit','Body mass units',[['lb','lb'],['kg','kg']]),n('minutes','Completion time — whole minutes',0,120,1),n('seconds','Completion time — seconds',0,59,1),n('hr','Heart rate at finish (beats/min)',1,250,1)],required:['age','sex','weight','weightUnit','minutes','seconds','hr'],check:['Which heart rate belongs in this equation?',['Final walking heart rate','Pulse after several minutes of rest'],0],limit:'The equation was developed in adults aged 30–69. Estimates in younger students and other populations need caution; this is not respiratory gas analysis.',extra:'Earlier in this course, VO₂ was measured using respiratory gas analysis. How is this assessment different?'},
{id:'ymca',name:'YMCA 3-Minute Step Test',group:'cardio',measure:'Cardiorespiratory response assessed through recovery heart rate.',kind:'norm',sources:['ace'],protocol:'Use a 12-inch (30.5 cm) step for 3 minutes. Follow 96 metronome beats/min: up, up, down, down (24 complete cycles/min). Sit immediately. Begin counting within 5 seconds and count every heartbeat for one full minute.',perform:'12-inch step · 96 beats/min · 3 minutes · full 60-second recovery count. Then follow the instructor’s cool-down.',fields:[n('hr','Beats counted over the full recovery minute (beats)',1,250,1),age(),sex()],required:['hr','age','sex'],check:['When do you count recovery beats?',['A 15-second count multiplied by four','One full minute, beginning within 5 seconds'],1],limit:'The recovery count is performance evidence, not a directly measured VO₂max. The reference table’s original sample details are not fully reported in the ACE summary.'},
{id:'queens',name:'Queens College Step Test',group:'cardio',measure:'Cardiorespiratory fitness estimated from a standardized stepping task and recovery pulse.',kind:'prediction',sources:['queens','queensStudy'],protocol:'Use a 16.25-inch (41.3 cm) step for 3 minutes. Male-equation protocol: 24 cycles/min (96 beats/min). Female-equation protocol: 22 cycles/min (88 beats/min). Remain standing; count pulse for 15 seconds from second 5 through second 20 of recovery. Multiply the count by four.',perform:'16.25-inch step · selected cadence · 3 minutes · recovery pulse from seconds 5–20.',fields:[sex(),n('pulse','Recovery pulse count during seconds 5–20 (beats)',1,65,1),choice('cadence','Cadence performed',[['','Select cadence'],['24','24 cycles/min'],['22','22 cycles/min'],['other','Different cadence']])],required:['sex','pulse','cadence'],check:['How long is the pulse-count window?',['15 seconds, from second 5 to 20','A full recovery minute'],0],limit:'Originally developed with college-age participants. Prediction accuracy can vary by population. A changed step height or cadence does not match these equations.'},
{id:'bench',name:'YMCA Bench Press',group:'endurance',measure:'Upper-body muscular endurance at a fixed load and cadence.',kind:'descriptive',sources:['bench'],protocol:'With an instructor/spotter, use the YMCA load: 80 lb for the male protocol or 35 lb for the female protocol, including the bar. Set the metronome to 60 beats/min: one beat down, one beat up (30 repetitions/min). Lower the bar to the chest without bouncing and press to full elbow extension. Stop when cadence or correct technique cannot be maintained.',perform:'Spotter · assigned load · 60 beats/min · count only full repetitions. Stop immediately for pain or loss of control.',fields:[n('reps','Correct repetitions (reps)',0,1000,1),choice('load','Load performed',[['','Select load'],['80','80 lb'],['35','35 lb'],['other','Other instructor-approved load']]),txt('loadOther','If other, record load and units')],required:['reps','load'],limit:'No protocol-matched reference table has been selected for this version. The repetitions do not measure maximal strength; an altered load changes the assessment.'},
{id:'pushup',name:'Push-Up',group:'endurance',measure:'Upper-body muscular endurance through consecutive push-ups.',kind:'norm',sources:['ace'],protocol:'Choose the instructor-approved standard (toes) or modified (knees) version. Keep the torso aligned. Lower the chest to the instructor’s fist/towel/block and return to full elbow extension. Perform consecutive repetitions without resting. Stop at inability to complete a repetition or two consecutive technique errors.',perform:'Record the version actually performed and count only correct repetitions.',fields:[n('reps','Correct repetitions (reps)',0,1000,1),choice('version','Version performed',[['','Select version'],['standard','Standard — toes'],['modified','Modified — knees'],['other','Other adaptation']]),age(),sex()],required:['reps','version','age','sex'],limit:'CSEP/ACE comparisons pair male reference scores with standard push-ups and female reference scores with modified push-ups. Anyone may perform either version, but a mismatched reference/version receives a descriptive result.'},
{id:'curlup',name:'YMCA Half Sit-Up / Curl-Up',group:'endurance',measure:'Trunk/abdominal muscular endurance over one minute.',kind:'descriptive',sources:['phenx'],protocol:'Place tape markers 3.5 inches (8.9 cm) apart. Lie face up with knees at 90° and feet flat, unanchored. Keep palms on the mat. Curl up until fingertips reach the second marker; return shoulders to the mat. Count correctly completed repetitions in one minute.',perform:'Mat · two markers 3.5 inches apart · feet unanchored · 60 seconds.',fields:[n('reps','Correct repetitions in one minute (reps)',0,200,1)],required:['reps'],limit:'This is the one-minute YMCA half sit-up. Norms for a different curl-up (arms crossed, cadence-based, or unlimited duration) would not match it, so no classification is assigned.'},
{id:'plank',name:'Plank Hold',group:'endurance',measure:'Trunk muscular endurance while maintaining a prone forearm plank.',kind:'norm',sources:['plank'],protocol:'After a brief practice, rest before the timed trial. Support the body on forearms and toes, elbows beneath shoulders, legs straight, and body aligned. Time the hold. Stop at voluntary fatigue or technique failure; the published protocol permits up to two corrective cues before stopping.',perform:'Forearms and toes · aligned trunk · stopwatch · instructor checks position.',fields:[n('time','Hold time (seconds)',0,3600),age(),sex(),choice('college','Is the college-age reference context appropriate?',[['','Select'],['yes','Yes — college-age comparison'],['no','No — descriptive result']])],required:['time','age','sex','college'],limit:'Strand et al. studied 471 college students, with mean ages about 20 years. Percentile bands are context from that sample, not age-specific standards for all adults.'},
{id:'squat',name:'Body-Weight Squat',group:'endurance',measure:'Lower-body muscular endurance performance under a classroom squat protocol.',kind:'descriptive',sources:['class'],protocol:'EXS101 classroom protocol: feet about shoulder-width, hands at hips, heels on the floor. Squat under control to the instructor’s agreed target depth (thighs approximately parallel), then stand fully. Count correct repetitions in 60 seconds. Stop if form or target depth cannot be maintained. Record any instructor-approved adaptation.',perform:'60 seconds · agreed depth · full standing position · correct repetitions only.',fields:[n('reps','Correct repetitions in 60 seconds (reps)',0,200,1),txt('adaptation','Protocol adaptation — optional')],required:['reps'],limit:'This is a classroom performance measure, not a validated population classification. Body proportions, depth, pace, and technique affect the result. No unrelated squat norms are used.'},
{id:'sitreach',name:'Sit-and-Reach',group:'flexibility',measure:'Reach performance involving the hips, hamstrings, and trunk in this specific movement.',kind:'norm',sources:['ace'],protocol:'For the ACE yardstick version, sit shoeless with knees straight, feet about 12 inches apart, and heels at the 15-inch (38.1 cm) mark. Reach slowly with aligned fingertips and hold about 2 seconds. Complete three trials; record the farthest reading. If using a different box or zero point, record that convention and use a descriptive result.',perform:'Record the scale reading, not automatically distance beyond the toes. Keep knees straight; do not bounce.',fields:[choice('convention','Measurement convention performed',[['','Select convention'],['ace15','ACE yardstick — heels at 15 in / 38.1 cm'],['toes0','Toes at 0 — signed distance beyond/before toes'],['box','Other box / zero point']]),choice('unit','Distance units',[['in','in'],['cm','cm']]),...trials('(scale reading)',150).map(f=>({...f,min:-150})),txt('box','Other convention: box/zero-point description'),age(),sex()],required:['convention','unit','trial1','age','sex'],limit:'Reach performance is influenced by body proportions and technique. It does not establish total-body flexibility. The reference comparison is available only for the ACE 15-inch-heel convention.'},
{id:'shoulder',name:'Shoulder Flexibility',group:'flexibility',measure:'Combined shoulder reach-over/reach-under movement, recorded as fingertip gap or overlap.',kind:'descriptive',sources:['class'],protocol:'Classroom back-scratch recording: reach one hand over the same shoulder and the other up the back. Without pulling or forcing, measure fingertip gap or overlap. Repeat with the opposite hand on top. Record gap as negative, touching as zero, and overlap as positive.',perform:'Record both sides (which hand is on top). Stop for pain; do not force the reach.',fields:[n('right','Right hand on top — signed distance (cm)',-100,100),n('left','Left hand on top — signed distance (cm)',-100,100)],required:['right','left'],limit:'This provides information about this particular shoulder movement. It does not establish overall flexibility or diagnose a shoulder condition. No reference population has been selected.'},
{id:'vertical',name:'Vertical Jump',group:'power',measure:'Lower-body explosive performance represented by countermovement jump height.',kind:'descriptive',sources:['jump','class'],protocol:'Classroom jump-and-reach protocol: measure standing reach with feet flat. From a stationary two-foot stance, use a countermovement and arm swing, jump, and touch as high as possible. No approach steps. Measure jump reach minus standing reach. Complete up to three valid trials, resting between trials; use the best height.',perform:'Record jump HEIGHT for each trial (jump reach minus standing reach). Use the same method for every trial.',fields:[choice('unit','Jump height units',[['cm','cm'],['in','in']]),...trials('(jump height)',200),txt('device','Measurement method/device')],required:['unit','trial1','device'],limit:'Jump height is a distance, not power in watts. Arm swing, technique, and measurement device affect performance. No protocol- and population-matched reference table has been selected.'},
{id:'broad',name:'Standing Broad Jump',group:'power',measure:'Horizontal lower-body explosive performance represented by jump distance.',kind:'descriptive',sources:['class'],protocol:'Classroom protocol: stand with both feet behind the takeoff line. Use a countermovement and arm swing; take off and land on both feet. Measure from the line to the nearest heel. An unstable landing or step/fall backward invalidates that trial. Complete up to three valid trials with rest; record the best distance.',perform:'Stationary start · two-foot takeoff/landing · measure to the nearest heel · valid trials only.',fields:[choice('unit','Jump distance units',[['cm','cm'],['in','in']]),...trials('(distance)',500)],required:['unit','trial1'],limit:'Distance is performance evidence, not direct power in watts. No protocol/population-specific normative dataset has been selected.'},
{id:'bia',name:'BIA — Optional',group:'body',measure:'Body composition estimated from bioelectrical impedance and a device prediction model.',kind:'estimate',sources:['bia'],protocol:'Use the available device according to its manufacturer instructions and instructor guidance. Record only the selected output; do not enter medical information.',perform:'Optional. Follow the device setup and testing conditions; no explanation is required to skip.',fields:[n('fat','Estimated body fat (%)',0,100),txt('device','Device/model')],required:['fat','device'],limit:'This is an estimate rather than direct measurement of body fat. Hydration, recent activity, food/beverage intake, and device models can affect it.',extra:'What factors could influence this estimate?'},
{id:'fit3d',name:'Fit3D — Optional / As Available',group:'body',measure:'A selected output from a 3D surface scan and its measurement/modeling system.',kind:'estimate',sources:['fit3d'],protocol:'Follow instructor and Fit3D scanner directions. Record only the relevant output selected by the instructor; do not upload a scan or enter medical information.',perform:'Optional and as available. Identify whether the selected output is a surface measurement or a modeled estimate.',fields:[choice('output','Output recorded',[['','Select output'],['fat','Estimated body fat (%)'],['other','Other instructor-selected output']]),n('value','Output value',0,10000),txt('label','If other: output name'),txt('unit','If other: units'),txt('device','System/device or software version'),choice('method','How is this output produced?',[['','Select'],['estimate','Modeled estimate'],['measurement','Surface measurement']])],required:['output','value','device','method'],limit:'Fit3D derives surface measurements from a scan and uses modeling for outputs such as estimated body fat. Different output types have different limitations.'}
];
// Data transcribed from ACE Tables 1–2, p.3: ascending recovery beats at descending percentiles.
const STEP_PERCENTILES=[100,95,90,85,80,75,70,65,60,55,50,45,40,35,30,25,20,15,10,5,0];
const STEP_NORMS={male:[[50,71,76,79,82,84,88,90,93,95,97,100,102,105,107,111,114,119,124,132,157],[51,70,76,79,83,85,88,91,94,96,100,102,104,108,110,114,118,121,126,134,161],[49,70,76,80,84,88,92,95,98,100,101,105,108,111,113,116,119,124,130,138,163],[56,77,82,87,89,93,95,99,101,103,107,111,113,117,119,121,124,126,131,139,159],[60,71,77,86,91,94,97,99,100,103,105,109,111,115,117,119,123,128,131,136,154],[59,74,81,87,91,92,94,97,102,104,106,110,114,116,118,121,123,126,130,136,151]],female:[[52,75,81,85,89,93,96,98,102,104,108,110,113,116,120,122,126,131,135,143,169],[58,74,80,85,89,92,95,98,101,104,107,110,113,116,119,122,126,129,134,141,171],[51,77,84,89,92,96,100,102,104,107,109,112,115,118,120,124,128,132,137,142,169],[63,85,91,95,98,101,104,107,110,113,115,118,120,121,124,126,128,132,137,143,171],[60,83,92,97,100,103,106,109,111,113,116,118,119,123,127,129,131,135,141,147,174],[70,85,92,96,98,101,104,108,111,116,120,121,123,125,126,128,129,133,135,145,155]]};
// CSEP/ACE Table 3, p.5: ascending category lower bounds, ages 20–59.
const PUSH_NORMS={male:[[17,22,29,36],[12,17,22,30],[10,13,17,25],[7,10,13,21]],female:[[10,15,21,30],[8,13,20,27],[5,11,15,24],[2,7,11,21]]};
// ACE Table 18, p.29: inch scale readings, heels at 15 inches.
const REACH_NORMS={male:[[11,13,14,15,17,18,19,20,22],[9,11,13,14,15,17,17,19,21],[7,11,13,13,15,16,17,19,21],[6,9,10,11,13,14,15,17,19],[5,7,9,9,11,13,13,15,17],[4,7,8,9,10,12,13,15,17]],female:[[14,16,17,18,19,20,21,22,24],[13,15,16,17,19,20,20,21,23],[12,14,15,16,17,18,19,21,22],[10,12,14,14,16,17,18,20,21],[9,11,13,14,15,16,17,19,20],[9,11,13,14,15,17,17,18,20]]};
const PLANK_NORMS={male:[62,79,89,97,110,122,137,157,201],female:[35,48,58,63,72,84,95,108,142]};
