'use strict';
// Local, dependency-free tagged PDF. Visible typography follows the Human Performance Lab.
// Each text line has a structural tag and Unicode ActualText in logical reading order.
function makeProfilePDF(blocks,meta){
 const PW=612,PH=792,M=48,W=516,objects=[''],add=s=>{objects.push(s);return objects.length-1;};
 const catalog=add(''),pagesRoot=add(''),structRoot=add(''),parentTree=add(''),documentTag=add('');
 const descriptors=[];const fonts=PDF_FONTS.map(f=>{const fontId=add(''),descriptor=add(`<< /Type /FontDescriptor /FontName /${f.name} /Flags 32 /FontBBox [${f.bbox.join(' ')}] /ItalicAngle 0 /Ascent ${f.ascent} /Descent ${f.descent} /CapHeight 730 /StemV 80 /FontFile2 ${objects.length+1} 0 R >>`),fontFile=add(`<< /Filter /ASCIIHexDecode /Length ${f.hex.length} /Length1 ${f.length} >>\nstream\n${f.hex}\nendstream`);descriptors.push(descriptor);objects[fontId]=`<< /Type /Font /Subtype /TrueType /BaseFont /${f.name} /FirstChar 32 /LastChar 126 /Widths [${f.widths.join(' ')}] /Encoding /WinAnsiEncoding /FontDescriptor ${descriptor} 0 R >>`;return fontId;});
 const ascii=s=>String(s).replace(/₂/g,'2').replace(/₁/g,'1').replace(/[–—−]/g,'-').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/→/g,' -> ');
 const escape=s=>s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
 const utf16=s=>'FEFF'+Array.from({length:s.length},(_,i)=>s.charCodeAt(i).toString(16).padStart(4,'0')).join('');
 const chars=[...new Set(blocks.flatMap(b=>[...String(b.text)]))],codes=new Map(chars.map((c,i)=>[c,i+1]));
 const cmapLines=['/CIDInit /ProcSet findresource begin','12 dict begin','begincmap','/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def','/CMapName /UnicodeText def','/CMapType 2 def','1 begincodespacerange','<0000> <FFFF>','endcodespacerange'];
 for(let i=0;i<chars.length;i+=100){const batch=chars.slice(i,i+100);cmapLines.push(batch.length+' beginbfchar',...batch.map((c,j)=>'<'+(i+j+1).toString(16).padStart(4,'0')+'> <'+utf16(c).slice(4)+'>'),'endbfchar');}
 cmapLines.push('endcmap','CMapName currentdict /CMap defineresource pop','end','end');const cmap=cmapLines.join('\n'),cmapId=add(`<< /Length ${cmap.length} >>\nstream\n${cmap}\nendstream`);
 const gid='00'.repeat((chars.length+1)*2)+'>';const gidId=add(`<< /Filter /ASCIIHexDecode /Length ${gid.length} >>\nstream\n${gid}\nendstream`);
 const descendant=add(`<< /Type /Font /Subtype /CIDFontType2 /BaseFont /DejaVuSans /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor ${descriptors[0]} 0 R /CIDToGIDMap ${gidId} 0 R /DW 500 >>`),unicodeFont=add(`<< /Type /Font /Subtype /Type0 /BaseFont /DejaVuSans /Encoding /Identity-H /DescendantFonts [${descendant} 0 R] /ToUnicode ${cmapId} 0 R >>`);
 const encoded=s=>[...s].map(c=>codes.get(c).toString(16).padStart(4,'0')).join('');
 const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');
 function width(s,size,bold){const display=ascii(s);if(/^[\x20-\x7e]*$/.test(display))return [...display].reduce((sum,c)=>sum+PDF_FONTS[bold?1:0].widths[c.charCodeAt(0)-32],0)*size/1000;ctx.font=`${bold?'bold ':''}${size}px Arial`;return ctx.measureText(display).width;}
 function wrap(s,size,bold,maxWidth=W){const lines=[];String(s).split('\n').forEach(p=>{let line='';for(const word of p.split(/\s+/)){if(width(line+(line?' ':'')+word,size,bold)>maxWidth){if(line)lines.push(line);line='';if(width(word,size,bold)>maxWidth){let part='';for(const c of word){if(width(part+c,size,bold)>maxWidth){lines.push(part);part='';}part+=c;}line=part;continue;}}line+=(line?' ':'')+word;}lines.push(line);});return lines;}
 const pageList=[],allTags=[];let page,y,currentSection='';
 function newPage(){page={id:add(''),commands:[],tags:[],images:[]};pageList.push(page);y=50;if(currentSection){line(currentSection+' (continued)','H2',9,true);y+=7;}}
 function ensure(h){if(y+h>720)newPage();}
 function raster(s,x,top,size,bold){const display=ascii(s);ctx.font=`${bold?'bold ':''}${size*3}px Arial`;canvas.width=Math.ceil(ctx.measureText(display).width)+6;canvas.height=Math.ceil(size*4);ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font=`${bold?'bold ':''}${size*3}px Arial`;ctx.fillStyle='#1f2937';ctx.fillText(display,0,size*3);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let hex='';for(let i=0;i<data.length;i+=4)hex+=data[i].toString(16).padStart(2,'0')+data[i+1].toString(16).padStart(2,'0')+data[i+2].toString(16).padStart(2,'0');hex+='>';const id=add(`<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /ASCIIHexDecode /Length ${hex.length} >>\nstream\n${hex}\nendstream`);page.images.push(id);page.commands.push(`q ${canvas.width/3} 0 0 ${canvas.height/3} ${x} ${PH-top-size/3} cm /Im${page.images.length} Do Q`);}
 function line(s,tag,size,bold,x=M){ensure(17);const mcid=page.tags.length,tagId=add(`<< /Type /StructElem /S /${tag} /P ${documentTag} 0 R /Pg ${page.id} 0 R /K ${mcid} >>`);page.tags.push(tagId);allTags.push(tagId);page.commands.push(`/${tag} << /MCID ${mcid} /ActualText <${utf16(s)}> >> BDC`);const display=ascii(s);
  if(/[^\x20-\x7e]/.test(display)){raster(s,x,y,size,bold);page.commands.push(`BT /F3 ${size} Tf 3 Tr ${x} ${PH-y} Td <${encoded(s)}> Tj 0 Tr ET`);}else page.commands.push(`${bold?'0.12 0.18 0.24':'0.12 0.16 0.21'} rg BT /${bold?'F2':'F1'} ${size} Tf ${x} ${PH-y} Td (${escape(display)}) Tj ET`);page.commands.push('EMC');y+=size+5;
 }
 function tableBlock(block){const widths=block.widths||[290,226],draw=(row,header=false)=>{const cells=row.map((v,i)=>wrap(v,9,header,widths[i]-14));let offset=0;const count=Math.max(...cells.map(c=>c.length));while(offset<count){if(y+30>720){newPage();if(!header)draw(block.headers,true);}const take=Math.min(count-offset,Math.max(1,Math.floor((720-y-12)/14))),height=take*14+12,top=y;let x=M;
 if(header)page.commands.push(`/Artifact BMC 0.91 0.96 0.95 rg ${M} ${PH-top-height+10} ${W} ${height} re f EMC`);
 for(let i=0;i<cells.length;i++){page.commands.push(`/Artifact BMC 0.72 0.79 0.8 RG 0.4 w ${x} ${PH-top-height+10} ${widths[i]} ${height} re S EMC`);y=top;for(const text of cells[i].slice(offset,offset+take))line(text,header?'TH':i===0?'TH':'TD',9,header,x+7);x+=widths[i];}y=top+height;offset+=take;if(offset<count){newPage();if(!header)draw(block.headers,true);}}};
 ensure(54);draw(block.headers,true);for(const row of block.rows){const h=Math.max(...row.map((v,i)=>wrap(v,9,false,widths[i]-14).length))*14+12;if(h<600&&y+h>720){newPage();draw(block.headers,true);}draw(row);}y+=9;
 }
 newPage();for(let i=0;i<blocks.length;i++){const block=blocks[i];if(block.tag==='TABLE'){tableBlock(block);continue;}
 if(block.tag==='H2')currentSection='';const bold=block.tag!=='P',size=block.tag==='H1'?12:block.tag==='H2'?9:block.tag==='H3'?9:block.small?8:10;
 if(block.tag==='H2'){ensure(120);y+=9;page.commands.push(`/Artifact BMC 0.55 0.68 0.67 RG 0.5 w ${M} ${PH-y+13} m ${M+W} ${PH-y+13} l S EMC`);}
 else if(block.tag==='H3'){const next=blocks[i+1],needed=next?.tag==='P'?Math.min(3,wrap(next.text,10,false).length)*15:20;ensure(35+needed);y+=3;}
 const display=block.tag==='H2'?block.text.toUpperCase():block.text,lines=wrap(display,size,bold);if(!bold&&lines.length<=5)ensure(lines.length*(size+5)+5);for(let j=0;j<lines.length;j++){if(j===lines.length-2)ensure((size+5)*2);line(lines[j],block.tag,size,bold);}if(block.tag==='H2')currentSection=block.text;y+=block.tag==='H3'?1:5;
 }
 for(let i=0;i<pageList.length;i++){const p=pageList[i];const footer=`Fitness Assessment Lab | ${meta.date} | Page ${i+1} of ${pageList.length}`;p.commands.push(`/Artifact BMC BT /F1 8 Tf 48 32 Td (${escape(ascii(footer))}) Tj ET EMC`);const content=p.commands.join('\n'),stream=add(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);objects[p.id]=`<< /Type /Page /Parent ${pagesRoot} 0 R /MediaBox [0 0 ${PW} ${PH}] /StructParents ${i} /Tabs /S /Resources << /Font << /F1 ${fonts[0]} 0 R /F2 ${fonts[1]} 0 R /F3 ${unicodeFont} 0 R >> /XObject << ${p.images.map((id,j)=>'/Im'+(j+1)+' '+id+' 0 R').join(' ')} >> >> /Contents ${stream} 0 R >>`;}
 objects[catalog]=`<< /Type /Catalog /Pages ${pagesRoot} 0 R /Lang (en-US) /MarkInfo << /Marked true >> /StructTreeRoot ${structRoot} 0 R /ViewerPreferences << /DisplayDocTitle true >> >>`;
 objects[pagesRoot]=`<< /Type /Pages /Kids [${pageList.map(p=>p.id+' 0 R').join(' ')}] /Count ${pageList.length} >>`;
 objects[structRoot]=`<< /Type /StructTreeRoot /K [${documentTag} 0 R] /ParentTree ${parentTree} 0 R /ParentTreeNextKey ${pageList.length} >>`;
 objects[documentTag]=`<< /Type /StructElem /S /Document /P ${structRoot} 0 R /K [${allTags.map(id=>id+' 0 R').join(' ')}] >>`;
 objects[parentTree]=`<< /Nums [${pageList.map((p,i)=>i+' ['+p.tags.map(id=>id+' 0 R').join(' ')+']').join(' ')}] >>`;
 const info=add('<< /Title (EXS101 Fitness Assessment Lab - Assessment Profile) /Creator (EXS101 Fitness Assessment Lab) >>');let output='%PDF-1.7\n',offsets=[0];objects.slice(1).forEach((o,i)=>{offsets.push(output.length);output+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=output.length;output+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length} /Root ${catalog} 0 R /Info ${info} 0 R >>\nstartxref\n${start}\n%%EOF`;return new Blob([output],{type:'application/pdf'});
}

