// Shared qualitative teaching model for demo and activity.
const levels=["","Rest / daily activity","Easy continuous","Sustained exercise","Vigorous effort","Brief maximal effort"];const acts=[{g:"Everyday Activity",n:"Sitting Quietly",i:1,d:1800,x:"Very low ATP demand, but ATP production never stops."},{g:"Everyday Activity",n:"Standing",i:1,d:600,x:"Low demand with continuous ATP regeneration."},{g:"Everyday Activity",n:"Slow Walking",i:2,d:600,x:"Assumes an easy, continuous walk."},{g:"Everyday Activity",n:"Carrying Groceries",i:2,d:90,x:"A familiar short task with modest demand."},{g:"Everyday Activity",n:"Climbing Stairs",i:4,d:25,x:"ATP demand rises quickly for a short effort."},{g:"Exercise",n:"Brisk Walking",i:2,d:1200,x:"Moderate, sustained activity."},{g:"Exercise",n:"Easy Cycling",i:2,d:1800,x:"Sustainable ATP demand over a longer duration."},{g:"Exercise",n:"10 Bodyweight Squats",i:3,d:20,x:"A brief effort with rising ATP demand."},{g:"Exercise",n:"Resistance-Training Set",i:4,d:40,x:"High demand sustained for a short set."},{g:"Exercise",n:"1-Mile Run",i:4,d:420,x:"High demand sustained for several minutes."},{g:"Exercise",n:"5K Run",i:3,d:1500,x:"Sustained demand over a longer effort."},{g:"Exercise",n:"Long Bike Ride",i:2,d:3600,x:"Moderate demand maintained for a long time."},{g:"Maximal / Near-Maximal",n:"Heavy 1-Rep Lift",i:5,d:4,x:"Very high ATP demand for only a few seconds."},{g:"Maximal / Near-Maximal",n:"Vertical Jump",i:5,d:2,x:"Explosive ATP demand almost immediately."},{g:"Maximal / Near-Maximal",n:"100 m Sprint",i:5,d:12,x:"Maximal demand over a brief sprint."},{g:"Maximal / Near-Maximal",n:"400 m Run",i:5,d:65,x:"Very high demand sustained much longer than a short sprint."}];function dur(v){v=+v;return v<30?2+v:v<60?30+(v-30)*5:180+(v-60)*90}function fmt(s){return s<60?Math.round(s)+" sec":s<3600?Math.round(s/60)+" min":(s/3600).toFixed(s%3600?1:0)+" hr"}function calc(I,D,q){const t=q*D,rest=I===1,early=t<=5,ongoing=t>120;
let p,g,o,n;
if(rest){p="ATP buffering";g="Basal contribution";o="Main sustained supply";n="This is an ongoing resting / daily-activity state, not the onset of maximal exercise. Oxidative metabolism supplies the sustained demand; phosphocreatine participates in ATP buffering. [1]";}
else if(early){p=I===5?"Especially important":"Rapid onset support";g=I>=4?"Rapidly activated":"Also contributes";o="Already contributing";n="At exercise onset, phosphagen and glycolytic processes respond rapidly while oxidative supply also contributes. Brief maximal work places particular emphasis on phosphagen ATP regeneration. This is an onset pattern, not a universal crossover time. [1]";}
else if(I<=3){p="Onset role subsides";g="Supports ATP supply";o=ongoing?"Main sustained supply":"Increasing support";n="For a sustainable continuous effort, oxidative ATP supply rises toward the ongoing demand. Glycolysis supports carbohydrate metabolism too; oxidative supply does not mean glycolysis switches off. [1]";}
else if(I===4){p="Initial stores limited";g="Important rapid supply";o="Substantial support";n="Vigorous effort draws on glycolytic and oxidative supply. The precise balance cannot be inferred from effort and time alone. Fatigue or reduced power can occur when demand exceeds sustainable supply. [1,2]";}
else{p="Initial role declines";g="Important rapid supply";o="Rising contribution";n="As an all-out effort continues, phosphocreatine availability falls; glycolytic and oxidative contributions remain important. All-out effort does not mean constant maximal power. No exact split is predicted here. [1,2]";}
return{p,g,o,n,d:levels[I],t};}

// Schematic visual trajectories: drawing coordinates, not measured ATP rates or percentages.
function visualRoles(I,t){
 if(I===1)return {p:12,g:18,o:85};
 const onset=Math.exp(-t/12),rise=1-Math.exp(-t/35);
 return {p:12+(I===5?78:45)*onset,
 g:18+(I>=4?57:22)*(1-Math.exp(-t/5))*Math.exp(-t/(I>=4?140:60)),
 o:18+(I>=4?55:67)*rise};
}
